Union Types
php/php-rfcs pull request #1
Opened 2019-09-04 08:11 UTC by nikic

Proposal for the addition of union types `T1|T2|...`. There has been a [previous proposal](https://wiki.php.net/rfc/union_types) on this topic, which has been declined.

2019-09-04 08:35 UTC, carusogabriel commented on rfcs/0000-union-types-v2.md
> +The [interaction with union types](https://wiki.php.net/rfc/typed_properties_v2#future_interaction_with_union_types) was already considered at the time, because it impacts the the detailed reference
```suggestion
The [interaction with union types](https://wiki.php.net/rfc/typed_properties_v2#future_interaction_with_union_types) was already considered at the time, because it impacts the detailed reference semantics. Repeating the example given there:
```

2019-09-04 08:35 UTC, carusogabriel commented on rfcs/0000-union-types-v2.md
> +The `__toString()` method returns a string representation of the type that constitus a valid code representation of the type in a non-namespaced context. It is not necessarily the same as what was us
```suggestion
The `__toString()` method returns a string representation of the type that consists of a valid code representation of the type in a non-namespaced context. It is not necessarily the same as what was used in the original code. Notably this *will* contain the leading `?` for nullable types and not be bug-compatible with `ReflectionNamedType`.
```

2019-09-04 08:35 UTC, carusogabriel commented on rfcs/0000-union-types-v2.md
> +This illustrates that the `false` pseudo-type in unions is nececessary to express the return type of many existing internal functions.
```suggestion
This illustrates that the `false` pseudo-type in unions is necessary to express the return type of many existing internal functions.
```

2019-09-04 08:46 UTC, carusogabriel commented
Discussions about the previous RFC:
- Discussion: https://externals.io/message/92274 and https://externals.io/message/93713
- Voting: https://externals.io/message/93953

2019-09-04 08:46 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +The `__toString()` method returns a string representation of the type that constitus a valid code representation of the type in a non-namespaced context. It is not necessarily the same as what was us
This was supposed to be "constitutes". Fixed in https://github.com/php/php-rfcs/pull/1/commits/8839f654923a56b8c589aff24e76a8d5323ad92d.

2019-09-04 08:53 UTC, AegirLeet commented
I really like it. I've encountered many situations where I wanted a method to accept multiple types while retaining type safety. The solution so far was using docblock type hints + static analysis + runtime checks. Union types on a language level would be a much nicer solution!

In addition to the nullable (`?Type`) and `iterable` types mentioned in the introduction, isn't `callable` another union type, since it can be either an `array` (with certain criteria), a `string` (with certain criteria) or a `Closure`?

2019-09-04 09:14 UTC, Ocramius requested changes

2019-09-04 09:14 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +
I think some clarity on why `true` is not included as a pseudo-type is needed here.

2019-09-04 09:14 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +For example, if `A` and `B` are class aliases, then `A|B` remains a legal union type, even though it could be reduced to either `A` or `B`. Similarly, if `class B extends A {}`, then `A|B` is also a
Wouldn't it be feasible to at least detect the imported symbols (according to `use` syntax within the current scope), and prevent duplicate usage of following?

```php
use Something as A;
use Something as B;

function foo(A|B $_) {} // expecting an error here
```

Or is this example simply missing?

2019-09-04 09:14 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +Additionally, the `iterable` type is considered to be the same (i.e. both subtype and supertype) as `array|Traversable`.
Rules about `false` and `bool` to be specified here

2019-09-04 09:14 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +When `strict_types` is not enabled, scalar type declarations are subject to limited implicit type coercions. These are problematic in conjunction with union types, because it is not always obvious wh
I'm generally a proponent for strict types, but what would the impact here be, if we assumed all union types to be strict instead? 

Not super-important, since the section just magically "disappears" when using a more reliable `declare(strict_types=1);`

2019-09-04 09:14 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +    /** @return ReflectionType[] */
How does this API behave when `?(Foo|Bar)` is the type?

2019-09-04 09:14 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +We've held off on adding a `mixed` type out of fear that it would be used in cases where a more specific union could have been specified. Once union types are supported, it would probably also make s
Another note is that `mixed|Foo` may probably be rejected by the parser (in future), since `mixed|Foo` can be implicitly reduced to `mixed` at all times

2019-09-04 09:16 UTC, asgrim commented on rfcs/0000-union-types-v2.md
> +
> A `true` pseudo-type is *not* part of the proposal, because similar historical reasons for its necessity do not exist.
it's already there ;)

2019-09-04 09:21 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +
Fair enough. A bit weak, IMO, so if there isn't much complexity involved, I'd suggest introducing it to reduce the edge cases.

2019-09-04 09:23 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +When `strict_types` is not enabled, scalar type declarations are subject to limited implicit type coercions. These are problematic in conjunction with union types, because it is not always obvious wh
I think that would be a bad idea for two reasons: First, it just seems wrong that if you go from `float` to `int|float` you end up accepting *strictly less* inputs, despite the type being nominally wider. Second, it will really wreck variance, because we can no longer say that `int` is a subtype of `int|float` etc.

2019-09-04 09:25 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +When `strict_types` is not enabled, scalar type declarations are subject to limited implicit type coercions. These are problematic in conjunction with union types, because it is not always obvious wh
Yep, makes sense: didn't think of how variance influences non-strict types, and indeed, this could cause BC breaks in very deep dependencies of a system.

2019-09-04 09:27 UTC, beberlei commented on rfcs/0000-union-types-v2.md
> +When `strict_types` is not enabled, scalar type declarations are subject to limited implicit type coercions. These are problematic in conjunction with union types, because it is not always obvious wh
I want to use this in non strict code :-) So basically probably a bunch of no votes ;-)

2019-09-04 09:29 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +    /** @return ReflectionType[] */
In this case `allowsNull()` would return true and `getTypes()` would return `[ReflectionType(Foo), ReflectionType(Bar)]`.

I'm definitely not a fan of the `allowsNull()` thing, and my preference would to to represent this type as `ReflectionNullableType(ReflectionUnionType([ReflectionType(Foo), ReflectionType(Bar)]))` instead. The only problem is that the existing `ReflectionNamedType` already uses the `allowsNull()` approach, instead of using a separate class to indicate nullability.

2019-09-04 09:31 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +    /** @return ReflectionType[] */
Can we add a note about this behavior for clarity then?

2019-09-04 09:32 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +    public function allowsNull();
This method is inherited - can be elided from the declaration

2019-09-04 09:32 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +    public function __toString();
This method is inherited - can be elided from the declaration

2019-09-04 09:36 UTC, deleugpn commented on rfcs/0000-union-types-v2.md
> +
Was `?|T1|T2` considered as an alternative to the mandatory parenthesis `?(T1|T2)`? I agree that `T|null` would have been better and also agree that it might be worst at this point, but I also feel like the parenthesis approach is cumbersome and if no technical challenges exists, `?|T1|T2` would actually be closer to what would have been nice.

2019-09-04 09:43 UTC, sebastianbergmann commented
Appreciate the new RFC medium.

2019-09-04 09:54 UTC, marandall commented on rfcs/0000-union-types-v2.md
> +
As this is targeted at 8.0, I am inclined to think that T1|T2|null is the way to go. It goes against my usual preference for only a single way of expressing something, but with the advent of unions, the continued use of ? seems like something which will be looked back on 5 years from now with a sense of disappointment that it wasn't changed earlier.

It also conforms to what people expect from the traditional standards of docblocks, making it much more intuitive.

2019-09-04 10:05 UTC, akalongman commented
This feature would be great! :heart_eyes:

2019-09-04 10:24 UTC, jderusse commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
What's about deprecating `?Foo` in favor of `Foo|null` the API will be much more consistent
```diff
 type: simple_type
     | union_type
-    | "?" simple_type
-    | "?" "(" union_type ")"
+    | "?" simple_type # deprecated
     ;
 simple_type: "false"          # only legal in unions
+           | "null"           # only legal in unions
            | "bool"
```

> I guess that if UnionTypes existed when Nullable had been implemented, that would have been the way to go

2019-09-04 10:30 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
I think it's too late to change course on this. What's more, for many cases, the `?type` syntax is actually quite expressive, for instance in my opinion `?LoggerInterface` more clearly reads as "maybe `LoggerInterface`" than `null|LoggerInterface`.

I do agree that _once you are using a union anyway_ the `?` form looks a bit odd, and listing `null` as one of the members of the union would be clearer, but I'm not sure how best to combine the two approaches.

2019-09-04 10:36 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +Proper enums are likely a better solution to this problem space, though depending on the implementation they may not be retrofitted to existing functions for backwards-compatibility reasons.
I would really love to see both custom types _and_ enums, as separate language features, so hope we keep the door open to both. In particular, I am strongly of the opinion that an enum value should _not_ be coercible to a plain type, because that leads to nonsense like `MONDAY == JANUARY`; as you say, that would rule out using them for existing function signatures. Custom types, meanwhile, could have more complex definitions - e.g. combining unions, intersections, constrained callables, and domains such as `int{>=0,<100}`.

2019-09-04 10:58 UTC, enumag commented on rfcs/0000-union-types-v2.md
> +    public A|B $prop;
Perhaps this should not be allowed at all? Since `A` type already includes `B` as well, using `A|B` type has no added value over just `A`.

2019-09-04 11:00 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +    public A|B $prop;
As noted elsewhere in the RFC, this can't be known in the general case at compile-time, because classes `A` and `B` may not have been defined yet.

2019-09-04 11:04 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +
I'm not sure what the 8.0 target has to do with it, but think allowing `T|null` _as well as_ `?T` may be the way to go. It can then be up to userland coding standards to enforce when to use each (e.g. `?int` but `int|float|null`) just as they will probably enforce consistent order of types (e.g. `int|float` vs `float|int`).

2019-09-04 11:08 UTC, marandall commented on rfcs/0000-union-types-v2.md
> +
> I'm not sure what the 8.0 target has to do with it

8.0 is lining up to be a **major** feature release, if ? was to become a semi-depreciated (not that I think it needs to be depreciated) then 8.0 would be the time to do it. Solve the problem of ? vs null as 8.0 hits, rather than waiting till 8.2 something like 5 years from now once everyone has been forced into using ?(Something|Like|This).

Prevention better than cure.

2019-09-04 11:10 UTC, tsantos84 commented
Type aliases is great.

2019-09-04 11:25 UTC, rybakit commented on rfcs/0000-union-types-v2.md
> + * RFC PR: [php-src/rfcs#0000](https://github.com/php-src/rfcs/pull/0000)
```suggestion
 * RFC PR: [php-rfcs/pull/1](https://github.com/php/php-rfcs/pull/1)
```

2019-09-04 11:36 UTC, kocsismate commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
And what about allowing `?`only for simple types, and `|null` only for union types? In my opinion it would be much readable than `?(SIMPLE_TYPE|SIMPLE_TYPE|...)`, although I notice that refactoring from simple type to union type and vice versa would need a little bit more effort.

2019-09-04 11:39 UTC, hikari-no-yume commented on rfcs/0000-union-types-v2.md
> +For example, if `A` and `B` are class aliases, then `A|B` remains a legal union type, even though it could be reduced to either `A` or `B`. Similarly, if `class B extends A {}`, then `A|B` is also a
This probably means `class_alias` and not `use`, right? The latter is basically syntactic sugar.

2019-09-04 11:41 UTC, deleugpn commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
Relevant: https://github.com/php/php-rfcs/pull/1#pullrequestreview-283493506

2019-09-04 11:44 UTC, hikari-no-yume commented
If an RFC is to be on Github and in Markdown anyway, I wonder if it couldn't be made as a pull request to the language specification repo instead. It could be beneficial to that spec for it not to be updated later after RFCs are passed, but instead the spec update could *be* the RFC. Perhaps this is too radical however :)

2019-09-04 11:47 UTC, hikari-no-yume commented on rfcs/0000-union-types-v2.md
> +We've held off on adding a `mixed` type out of fear that it would be used in cases where a more specific union could have been specified. Once union types are supported, it would probably also make s
But is that proper? Yes, to the runtime it provides no extra information, but is there a value in it as documentation of special handling of Foo?

2019-09-04 11:48 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +We've held off on adding a `mixed` type out of fear that it would be used in cases where a more specific union could have been specified. Once union types are supported, it would probably also make s
Not really, since `mixed` is an evil blob that swallows everything anyway (top type)

2019-09-04 11:54 UTC, muglug commented on rfcs/0000-union-types-v2.md
> +    public A|B $prop;
Yes and type analysers can do the complaining for you (though at least in my case it'll just treat as `public A $prop`).

2019-09-04 11:54 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +
I don't think that has anything to do with major versions. Either we introduce `Foo|Bar|null` with this RFC, or we introduce `?(Foo|Bar)` with this RFC. If the RFC doesn't get merged until 8.2, all the same pros and cons would apply; neither syntax is currently valid, so nobody is being forced to write it one way and then change to the other.

As for deprecation, see separate thread below for my thoughts on that.

2019-09-04 11:54 UTC, Ocramius approved these changes
:+1: 

The comments above are mostly tiny details, I think the proposal is very much sound and very welcome too.

2019-09-04 11:57 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
> And what about allowing `?`only for simple types, and `|null` only for union types? 

I think that's best left to coding standards; there's always going to be more than one way to write things (`int|float` vs `float|int`) and "`null` is allowed as a member of union types" is a lot simpler than "`null` is allowed as a member of union types, as long as there are at least two other members".

2019-09-04 12:06 UTC, muglug commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
I don’t quite understand we must be punished for past sins here. The original nullable types proposal wasn't expansive (it didn't allow for union types) so `|null` wasn't an option. But now it is and option, and I think it's better.

At work I see new-to-PHP developers tripped up by the `?` when helping them debug issues (where I have to explain that the `?` means nullable). Allowing `Foo|null` (as a synonym for `?Foo`) would make life a little easier, especially for those used to TypeScript (where `Foo|null` is valid).

I agree that having too ways to do things isn’t ideal, but allowing for slightly more verbosity isn't bad in my book.

2019-09-04 12:08 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
Side-note: fixing this would allow for a proper `null` type too (usable when a value is willingly discarded)

2019-09-04 12:09 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
@muglug Just to absolutely clear, my :-1: on the comment at the start of this thread is reacting to the suggestion of _deprecating `?T`_; I am marginally in favour of adding `T|null` as an _additional_ way to write it.

2019-09-04 12:38 UTC, muglug commented on rfcs/0000-union-types-v2.md
> +
Also not sure to put this discussion, I commented here: https://github.com/php/php-rfcs/pull/1#discussion_r320721511

2019-09-04 12:39 UTC, deleugpn commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
@IMSoP how do you imagine it for multiple parameters? I know `T1|T2|null` is obvious for that approach, but since your suggestion is allowing `|null` as an alternative to `?`, then would the `?(T1|T2)` still be forced to exist?
Personally I **only** don't like `?(T1|T2)`. I'm fine with `|null` being available only for Union or even being the only way for several nullable objects when using Union. As I said in the other thread, I'm even fine with `?|T1|T2`.

2019-09-04 12:41 UTC, freshp commented
I hope it is the right place to ask for something? Its the first RFC I read, thats why please be patient.
Excuse me too, if I misinterpreted the RFC but I dont find any example where I want to use this feature, besides nullability? 

IMO many programmers are going to use it like a mixed-typehint with "strict_types = 1". (something like : ":int|float|string|bool") Also IMO PHP was getting typified, harded, easier to read and write since version 7. Thx for that, but this feature could go in another direction. 

Maybe a realworld example could help me to understand, which sourcecode is getting easier to maintain or to write with this new feature?

2019-09-04 12:42 UTC, dbrekelmans commented on rfcs/0000-union-types-v2.md
> +### `false` pseudo-type
IMO adding the `false` pseudo-type because of library implementation details is the wrong choice. Adding a language-level feature to cope with a historical design flaw is only adding to the pile. It's legacy as soon as it's implemented.

I absolutely understand your reasoning. I myself would prefer to know a function cannot return true, but if typehinting `|bool` over `|false` is seen as such an issue, it should be fixed at the root (return null instead of false) instead of adding a band-aid.

2019-09-04 12:43 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
@deleugpn I'd personally be fine with `|null` being the only option to combine null with a union type, so that `?T1` was just a special case short-hand for `T1|null`. Some people might prefer the option of `?(T1|T2)` for a different kind of consistency, though, I guess.

2019-09-04 12:48 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +### `false` pseudo-type
I see what you're getting at, but rather than "legacy as soon as it's implemented" it could also be seen as a pre-cursor for a more general feature, where you can specify a union of _values_ rather than just _types_. See ["Literal Types" in the Future Scope section](https://github.com/nikic/php-rfcs/blob/union-types/rfcs/0000-union-types-v2.md#literal-types) for a brief discussion of this.

2019-09-04 12:50 UTC, deleugpn commented on rfcs/0000-union-types-v2.md
> +### `false` pseudo-type
Due to BC constraints, changes to return type like that have a devastating potential to break uncountable (_read infinite_) amount of code on the internet, affecting adoption rate for the upgrade. I don't think you are wrong to say it's legacy the moment it's implemented, but it's part of coping with the 20 years baggage of PHP.
I think discussing the merits of BC breaks is not worth anybody's time at this RFC as Internals have been debating that for several months already (that I know of).

2019-09-04 12:51 UTC, azjezz approved these changes

2019-09-04 12:52 UTC, sgolemon commented on rfcs/0000-union-types-v2.md
> +
I agree with @marandall.  We should regard `?type` as a special-case of the union `null|type` for null plus a single type only.  For null or multiple types, we should do this right and remove `?` from the picture, requiring `null|T1|T2` explicitly.

2019-09-04 12:53 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +Additionally, the `iterable` type is considered to be the same (i.e. both subtype and supertype) as `array|Traversable`.
Specified in https://github.com/php/php-rfcs/pull/1/commits/cf76009e2b153ba02f29a025f820bef86ae16f1f.

2019-09-04 12:54 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +When `strict_types` is not enabled, scalar type declarations are subject to limited implicit type coercions. These are problematic in conjunction with union types, because it is not always obvious wh
I added a section on this topic in https://github.com/php/php-rfcs/pull/1/commits/cf59fa5964f987d21c7d038d41791b80bd9e9b4d.

2019-09-04 12:56 UTC, sgolemon commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
As stated above, IMO we should continue to allow `?type` for null plus a single type, but require an explicit `null|T1|T2` for null plus multiple types (`null|type` would be allowed as well, of course).

Given that, I don't think the parenthesis are required for the proposal as it stands.  We may decide we want them for algebraic data types later on `(A|B)&(C|D)` at some point in the future, but they can easily be added at that time.

2019-09-04 12:58 UTC, Bigbear7 commented on rfcs/0000-union-types-v2.md
> +
Agree that true should be included as a pseudo type. Without reading the RFC one would assume it's included. It helps documentation & tutorials since no effort is needed to explain why it's not included.

2019-09-04 12:58 UTC, dbrekelmans commented on rfcs/0000-union-types-v2.md
> +### `false` pseudo-type
I'm certainly not proposing such a BC break and I agree let's avoid the BC discussion. I'd rather leave the wound exposed (typehint `|bool` where false is returned) than cover it up with this pseudo-type band-aid.

@IMSoP Looking at it that way, it makes more sense. :)

2019-09-04 12:58 UTC, dbrekelmans approved these changes

2019-09-04 13:00 UTC, sgolemon commented on rfcs/0000-union-types-v2.md
> +Property types are invariant, which means that types must stay the same during inheritance. However, the "same" type may be expressed in different ways. Prior to union types, one such possibility was
Just because I had to think this through for a moment, I'd suggest explaining why property types are invariant during inheritance. Specifically that setting a property would allow for contravariance, but that reading would only allow for covariance. The intersection of those rules is invariance.

2019-09-04 13:29 UTC, robbertstevens commented
I don't if it was already asked before, but why would you want this over method overloading? If a method accepts both a string and an integer wouldn't you want to have different behaviours in the method? 

In which method overloading creates a much clearer code base than a method that both handles a string and an integer.

2019-09-04 13:37 UTC, enumag commented on rfcs/0000-union-types-v2.md
> +    public A|B $prop;
I see, makes sense. Yeah, I'm sure PHPStan will handle this.

2019-09-04 13:41 UTC, bwoebi commented on rfcs/0000-union-types-v2.md
> +For example, if `A` and `B` are class aliases, then `A|B` remains a legal union type, even though it could be reduced to either `A` or `B`. Similarly, if `class B extends A {}`, then `A|B` is also a
@Ocramius `use` imports are typically resolved before any comparison (otherwise it'd also be possible to do an union of qualified and unqualified names). But for sure, that could be clarified here.

2019-09-04 13:41 UTC, beberlei commented
@robbertstevens Dan has aggregated the current state of why method overloading is probably never going to happen in PHP here: https://github.com/Danack/RfcCodex/blob/master/method_overloading.md

2019-09-04 13:44 UTC, msarca commented
There are some issues I would like to address. Union types are necessary, but I believe that some improvements must be made to this proposal.

### Type aliasing

Let's look at the following example.

```php
use Foo\bar;

function test(bar $bar) {
    // is $bar an object? 
}
```
If the `Foo\bar` type exists, then `$bar` is definitely an object. This is how it's been for years. But now, with the introduction of exported types, `$bar` could be anything. And this incertitude could prove to be a PITA in the long run.

```php
namespace Foo;
type bar = int|float;

// Usable as \Foo\bar from elsewhere
```

#### Proposal
Introduce use type. This way we could no longer make wrong assumptions.

```php
use Foo\bar;
use type Foo\baz;
use type int|float|string|bool as scalar; // local type

function test1(baz $baz, scalar $scalar) {
    // Don't make assumptions, check type definition.
}

function test2(bar $bar) {
    // It's an object
}
```

### Nullable types

Nullable types should not be allowed when defining a union type.
```php
use type ?(T1|T2|T3) as foo;
use type bar;

// What's this? Nullable nullable type?
function test(?foo $val) {
}

// Is bar nullable?
function test2(bar $val) {
   // Should I check if $val is null?
   if (is_null($val)) {
   }
}
```

#### Proposal
Keep it simple. No nullable types inside unions

```php
use type T1|T2|T3 as foo;

// Not nullable
function test(foo $val) {
    // $val can't be null
}

// Nullable
function test2(?foo $val) {
   // I should check if $val is null
   if (is_null($val)) {
   }
}
```

### Keep the syntax clean

There should be a single way of declaring a union type. The *in place* way of declaring a union type should be removed.

```php
use type float|int as number;

// Confusing..
function sum(float|int $a, int|float $b): number{
}

// ??
function example(int|float $value, int $flag = 2|4|8|16|32, string|object $item = null): float|int|false {
}
```

It's hard to read, hard to follow and the syntax is super ugly.

#### Proposal
Keep the syntax unchanged by forcing the user to either export a union type or declare it locally with the help of `use type`.

```php
use type float|int as number;

// Makes sense now..
function sum(number $a, number $b): number{
}
```

This way the `ReflectionUnionType ` is no longer necessary. Only the `ReflectionType` needs to be changed.

```php
class ReflectionType {
    isUnionType(): bool;
    getUnionTypes(): array;
}
```

Putting all together..

```php
type scalar=int|float|string|bool; // export union type
use type int|float as number; // local union type

class Foo
{
    private number $foo; // non-nullable property
    private ?number $bar; // nullable property
    
    // non-nullable arguments & return type
    function sum(number $a, number b):number {
    }
   
    // nullable arguments and return type
    function test(?scalar $value): ?scalar {
    }
}
```

2019-09-04 13:47 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +    public function allowsNull();
I've added comments to that effect in https://github.com/php/php-rfcs/pull/1/commits/256535b7f09239a106331374dc63028fd73029b1. However, I'd like to keep the declaration here so that the full exported API is visible. Otherwise it's not immediately clear how the null case is handled.

2019-09-04 13:48 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +    /** @return ReflectionType[] */
I've added some examples in https://github.com/php/php-rfcs/pull/1/commits/5bdd11ddb82cb6d4873accac0ccc03a16350cc1b that should make the behavior clear.

2019-09-04 13:49 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +    /** @return ReflectionType[] */
I've added some examples in https://github.com/php/php-rfcs/pull/1/commits/5bdd11ddb82cb6d4873accac0ccc03a16350cc1b to make the behavior more obvious.

2019-09-04 13:50 UTC, IMSoP commented
@msarca You seem to be assuming that "type aliases" will be implemented, but they are currently in the "Future Scope" section, and not part of this proposal. Did you misread the proposal, or are you saying that union types should not be allowed without expanding the proposal to include type aliases?

2019-09-04 14:05 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +We've held off on adding a `mixed` type out of fear that it would be used in cases where a more specific union could have been specified. Once union types are supported, it would probably also make s
> Another note is that `mixed|Foo` may probably be rejected by the parser (in future)

That is probably up to the Mixed RFC (either mine or someone else's) to address this, depending on whether union types land or not.

2019-09-04 14:16 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +
I pretty much dislike the fact that `|null` is forbidden, because:
1) `null` is a standalone (unit) type,
2) `?X` is a syntax sugar for `X|null` added in times when union types were not a thing.

[Nullable types RFC](https://wiki.php.net/rfc/nullable_types) also explicitly says that `?X` is a special type of union type and that if union types RFC gets accepted, `?X` will be equivalent to `X|null`.

It's also way more explicit and easier for readers to read `Foo|int|null` than `?(Foo|int)` -- this will become even harder to understand when nesting becomes common (intersection types).

For this very reason I would vote 👎 on this RFC.

2019-09-04 14:22 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +    public A|B $prop;
This should probably be moved to a separate section: `Known problems` or `Limitations` because while it should work as @enumag says, the engine doesn't make it possible ATM.

2019-09-04 14:24 UTC, robbertstevens commented
> @robbertstevens Dan has aggregated the current state of why method overloading is probably never going to happen in PHP here: https://github.com/Danack/RfcCodex/blob/master/method_overloading.md

Thanks I didn't know. I just want to add; I thought that method overloading is only used for your argument the return types should stay the same.

2019-09-04 14:25 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +    public function getTypes();
Any chance to split this method off to a separa0e `abstract ReflectionCompositeType`? It could later be used by `ReflectionIntersectionType` without moving this method around and allow forward-compatible code already.

2019-09-04 14:31 UTC, msarca commented
@IMSoP You are right, I was assuming that type aliases are part of the current proposal (totally missed that *Future scope* title).  I do believe that this proposal should include type aliases, otherwise is incomplete and if it is approved in the current form, in the long run, it will do more harm than good. The idea that we'll have **n!** ways of declaring the same type frightens me..

2019-09-04 14:54 UTC, IMSoP commented
@msarca While I like the idea of type aliases in general, I don't think it's essential. 

* One way to look at is that `int|float`, when used inline, isn't really a type, it's _a type constraint_, and let's you say "this is either an int or a float" without implying that there is some type combining the two.
* Another interpretation is that it's like anonymous functions and classes, both of which we already have.
* As for the number of ways the same type can be declared, demanding type aliases only removes one, you can still have an infinite number more just by having different names for the same composite type: `type foo = int|float; type bar = int|float; type foobar = float|int;`

2019-09-04 15:23 UTC, patrickallaert commented
Looks like for the first time, participating in the discussions of a PHP RFC is subjected to [Github's term of service](https://help.github.com/en/articles/github-terms-of-service).

2019-09-04 15:28 UTC, msarca commented
> I don't think it's essential.

@IMSoP  It's not essential, it's critical! There are four scalar types in PHP and if you want to use them all in an union type, there are 24 variants of arranging `int|float|bool|string`. Imagine you have multiple people working on a project and each one of them is using a different combination to express the same thing. Now imagine that you want to modify the union type by adding or removing a type. What happens then? That will quickly escalate into a refactoring nightmare! And it will happen all the time. But with type aliases, you make a change in one place and it's reflected everywhere. As I was saying, in the current form, if accepted, this proposal will do more harm than good.

2019-09-04 15:32 UTC, lisachenko commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
Is it possible to put all stuff into the `ReflectionType` itself to prevent violation of Liskov principle by checking instance of given type:
```php

$type = (new ReflectionMethod(SomeClass::class, 'method'))->getReturnType();
if ($type instanceof ReflectionUnionType) {
    // ... ok, we have a union type here
    $types = $type->getTypes();
} else {
    // not a union type here
}

2019-09-04 15:34 UTC, trowski commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
+1 for `|null`, though I see no harm in allowing `?(type|list)` as well if some prefer that syntax.

2019-09-04 15:36 UTC, lisachenko commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
Maybe provide list of simple methods in the `ReflectionType`, like `isUnion(): bool`, `getSubTypes(): array`?

2019-09-04 15:41 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
What do you mean by violation of LSP? Checking for instances doesn't violate LSP, composite types only extend behaviour of generic ReflectionType. (Also see [my comment about `ReflectionCompositeType` above](https://github.com/php/php-rfcs/pull/1#discussion_r320789714)).

Besides, `getSubTypes()` doesn't make sense on generic ReflectionType if the type is simple.

2019-09-04 16:36 UTC, patrickallaert commented
> > I don't think it's essential.
> 
> @IMSoP It's not essential, it's critical! There are four scalar types in PHP and if you want to use them all in an union type, there are 24 variants of arranging `int|float|bool|string`. Imagine you have multiple people working on a project and each one of them is using a different combination to express the same thing. Now imagine that you want to modify the union type by adding or removing a type. What happens then? That will quickly escalate into a refactoring nightmare! And it will happen all the time. But with type aliases, you make a change in one place and it's reflected everywhere. As I was saying, in the current form, if accepted, this proposal will do more harm than good.

I completely share @msarca's opinion.

Not to mention that QA tools may have to deal with the comparison of types `int|float|string|bool` vs `bool|float|int|string`.

Being able to use union types anonymously looks like being able to support anonymous interface with the same amount of duplication:
```php
function compute(
    interface { public function getValue(); } $value1,
    interface { public function getValue(); } $value2
): interface { public function getValue(); } {
    /*...*/
}
```

Funny enough: the absence of **named union types** support has encouraged the documentation of all possible param/return types in a very duplicated way. Officially supporting unaliased/unnamed types really misses one of the original issue of still writing phpdoc `@param`/`@return` unions.

If union types can be possibly defined everywhere **inline** (aka unaliased/unamed), I will vote :-1:, not because of the concept of union types, but because of not solving the current code duplication issue.

2019-09-04 16:59 UTC, muglug commented
> If union types can be possibly defined everywhere inline (aka unaliased/unamed), I will vote 👎, not because of the concept of union types, but because of not solving the current code duplication issue.

That really does seem like throwing the baby out with the bathwater.

An RFC doesn’t have to solve every problem for it to be a step in the right direction, and there are other obstacles to tackle before type aliases can be made to work (autoloading etc.). Indeed, I think this RFC provides a big positive impetus for type aliases (to avoid that duplication in the future).

2019-09-04 17:17 UTC, IMSoP commented
> @IMSoP It's not essential, it's critical! There are four scalar types in PHP and if you want to use them all in an union type, there are 24 variants of arranging `int|float|bool|string`. 

I'm not sure how having type aliases solves this. You could still have `type foo = int|float|bool|string` in one file and `type bar = string|int|float|bool` in another. The thing that will solve that, as with everything else that has multiple ways to do it, is coding standards.

> Now imagine that you want to modify the union type by adding or removing a type.

I think this is where we have completely different images of what an anonymous union type represents. To me, this is like saying "amend everywhere in the program that accepts an int and make it accept a string instead"; it makes no sense, because there is no connection between "all the places that accept an int". 

Take `str_replace` as an example: several of its arguments could be specified as `string|array`, but that doesn't mean that it accepts the same "type" as every other function that would be specified that way. Rather, the type annotation is an assertion: `assert(is_string($needle) || is_array($needle))`.

Type aliases make sense when you want to add some information beyond that assertion, but that's true even without a union. I'd love it if you could write `typedef timestamp = int`, and have strict mode require you to explicitly cast integer values to `timestamp`; but it would be bizarre if you _had_ to define that, and could no longer use `int` as a type annotation.

2019-09-04 18:08 UTC, patrickallaert commented
While the work on the RFC is splendid (thanks @nikic,), I think that rushing into the support of Union Types by just replacing some phpdoc with native PHP syntax is a naive approach.

There are currently several open issues:

1. Most `is_*()` functions can be avoided using typehint, it is not the case for `is_scalar()` and `is_numeric()`.
2. Many user-land unions represents the list of types that permits a certain operation, like "being used as a string" (`string|ObjectImplementing__ToString`), "can I foreach() on it", "can I json_encode() it", ...
3. Many user-land functions accept either a `Type` of a collection of `Type` as in: `Type|Type[]`.
4. With the support of `null`, we already embraced the [_The Billion Dollar Mistake_](https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/) a long time ago.
5. Some developers think there is nothing wrong in designing API involving: `@param float|int|array|Person|ValueAbstract|Printable|null|false $data`.

Issue 1. would be solved by this RFC, but in a very inconsistent way involving many different different ways of defining a _scalar_ and or a _numeric_, instead of (or additionally) providing some sort of `scalable`/`numeric` typehint, which could potentially be introduced without (un-aliased) union types.

Issue 2: this RFC would provide some sort of workaround, but would still miss the _intention_/_operation_ that is expected to work.

Issue 3 is only partially addressed as `Type|Type[]` can only become: `Type|array`. The phpdoc would remain and checking that every elements of the array is a `Type` still need to happen in code. That could be seen as a minor downside, but given the provided [stats](https://gist.github.com/nikic/64ff90c5038522606643eac1259a9dae) and the frequency of this pattern, it just can't ignored.

Issue 4 is not addressed by this RFC. While other languages ([Rust's `Option`](https://doc.rust-lang.org/std/option/index.html), [Kotlin](https://kotlinlang.org/docs/reference/null-safety.html)) have addressed the nullability issue, here we are **adding an exponent behind the "Billion"** as we could still solely rely on the typehint mechanism without having means to check that all possible types are correctly used and/or individually checked. I wish we could address the need for Union Types and the null safety issue with a unique `Option`-like approach.

Issue 5, yes, language abuse will always be possible, but quoting Sir Charles Antony Richard Hoare, we have a responsibility in not encouraging bad practice:
> Programming language designers should be responsible for the errors in programs written in that language

2019-09-04 18:18 UTC, Ocramius commented
> The Billion Dollar Mistake a long time ago.

The `null` issue is mostly a Java-only issue, where references are nullable by default (hence the nightmares it caused due to NPEs).

2019-09-04 18:22 UTC, patrickallaert commented
> An RFC doesn’t have to solve every problem for it to be a step in the right direction, and there are other obstacles to tackle before type aliases can be made to work (autoloading etc.). Indeed, I think this RFC provides a big positive impetus for type aliases (to avoid that duplication in the future).

Sure thing, the problem is that I cannot consider it as a step in the right direction considering that if aliases would be supported, I would consider that non aliased usage of union type should emit a deprecation notice or it's usage being dropped, which is not BC-friendly and well designed in the first place.

We should not introduce a feature F that would be questionable as soon as F' is implemented.

Or said differently: I question the concept of anonymous/un-aliased/un-named union types in the first place which would still exist if optional aliases would be introduced later.

2019-09-04 18:26 UTC, patrickallaert commented
> > The Billion Dollar Mistake a long time ago.
> 
> The `null` issue is mostly a Java-only issue, where references are nullable by default (hence the nightmares it caused due to NPEs).

So, if I search for "Call to a member function ...() on non-object" in PHP contexts, it should barely return 0 results, right?

The Billion Dollar Mistake has not been introduced in Java, but in ALGOL in 1965 and that mistake has been copied in many languages (including PHP).

2019-09-04 18:27 UTC, msarca commented
> I'm not sure how having type aliases solves this. You could still have type foo = int|float|bool|string in one file and type bar = string|int|float|bool in another.

Of course that someone could alias the same types but with different names: `type foo=int|float` and `type bar=int|float`. That's not an issue. We do this every day with classes and interfaces.

```php
use stdClass as x;
use stdClass as y;

function t(x $x, y $x) {
}
```

 But lets take the following code where we are using anonymous union types to define some type constraints for a series of **n** functions. As you can see our functions accept as an argument only valid JSON serializable values.

```php
function f_1(?(int|float|string|bool|array|\stdClass) $value) {
}
function f_2(?(int|float|string|bool|array|\stdClass) $value) {
}
// so on till..
function f_n(?(int|float|string|bool|array|\stdClass) $value) {
}
```

For the same functions lets use a named union type. Much simpler, right?

```php
type json = int|float|string|bool|array|\stdClass;

function f_1(?json $value) {
}
function f_2(?json $value) {
}
// so on till..
function f_n(?json $value) {
}
```

> I think this is where we have completely different images of what an anonymous union type represents. To me, this is like saying "amend everywhere in the program that accepts an int and make it accept a string instead"; it makes no sense, because there is no connection between "all the places that accept an int".

Indeed, we have. But now try to imagine that you are a business owner and start to receive complaints from your customers about the fact that your functions don't work with objects that implements the `JsonSerializable` interface, even though they should. Your developers totally missed that and now you need to refactor! It happens all the time.

Lets refactor first on anonymous union types.. It will take **n** modifications, one for each function.

```php
function f_1(?(int|float|string|bool|array|\stdClass|\JsonSerializable) $value) {
}
function f_2(?(int|float|string|bool|array|\stdClass\JsonSerializable) $value) {
}
// so on till..
function f_n(?(int|float|string|bool|array|\stdClass|\JsonSerializable) $value) {
}
```

But with named union types only 1 modification is necessary.

```php
type json = int|float|string|bool|array|\stdClass|\JsonSerializable;
```

And the real issue with these anonymous union types is the fact that you can't rely on search and replace because maybe one of your developers defined the constraint as being `?(int|float|string|bool|array|\stdClass)` and onther one as `?(\stdClass|array|float|string|bool` and no error was thrown because they are equivalent and valid.

2019-09-04 18:30 UTC, Ocramius commented
> So, if I search for "Call to a member function ...() on non-object" in PHP contexts, it should barely return 0 results, right?

You're gonna get a NPE type-check error from any IDE or tool like @phpstan or @vimeo/psalm. The same type of error would happen even on something like:

```php
class A {}
class B {
    function something() : void {}
}
function (A|B $p) : void
{
    $p->something();
}
```

It is not inherently an issue of `null`, but of type mismatch, which this RFC helps in detecting from a language PoV, while most responsible devs out there are adopting workarounds based on documentation and userland tools.

2019-09-04 19:42 UTC, msarca commented
@Ocramius I've exposed my opinion loud an clear, but it seems that you keep disagreeing with me. Do you have some counter-arguments or you're just trolling me? If you do have, I would really like to read them.

2019-09-04 20:01 UTC, nikic commented
@msarca **Moderation Note:** You have indeed made your opinion clear, and some people disagree with that opinion and have laid out their own arguments above. Accusation of trolling are neither warranted nor appropriate. Please take a step back.

I will likely comment more on the question of type aliases tomorrow, but for now let me say this: I **will not** include type aliases as part of this RFC. Type aliases (especially the exported kind) have some non-trivial design space that both deserves and requires a dedicated RFC to discuss the possibilities in detail. While the type alias feature is definitely symbiotic with union types, it is certainly not a requirement.

I would appreciate it if discussions of type aliases could be kept out of the union types RFC. Please do feel free to start a separate discussion on this topic on the internals mailing list, or maybe even collaborate on a type aliases RFC. Thanks.

2019-09-04 20:34 UTC, msarca commented
@nikic I will take a step back as you suggested, there's no need to artificially escalate this just because I don't want this RFC to pass. But for the sake of truth, there were no arguments brought in regard to the refactoring issue raised by me. Just "thumbs down emojy", which we both know that are not real arguments. If someone knows a better euphemism to describe this kind of arguments, I'm all ears. Thanks.

2019-09-04 20:38 UTC, claudepache commented on rfcs/0000-union-types-v2.md
> +
At this point, it may help the reader (at least, it would have helped me) if you add a table similar to the one of https://wiki.php.net/rfc/union_types#solution, so that, it becomes clear that this apparently arbitrary preference order gives usually what you want:

Original type | 1st try | 2nd try | 3rd try
--------|-------|--------|-------
bool    | int   | float  | string
int     | float | string | bool
float   | int   | string | bool
string  | int/float | bool
object  | string

(I note that there is one minor difference from the previous RFC.)

2019-09-04 21:27 UTC, tuqqu commented on rfcs/0000-union-types-v2.md
> +
I see no harm in adding `|null` as well as leaving `?type` as its shortcut for a single nullable type only.

2019-09-04 22:22 UTC, iquito commented on rfcs/0000-union-types-v2.md
> +
Having only the `|null` option in union types and the current `?type` as a "legacy" version only for a single type (with no deprecation anytime soon, or maybe ever) seems the best of both worlds to me. Establishing a union syntax with both ? and () just for null and to be consistent to something that is inherently inconsistent seems like fighting a problem with a bigger problem.

I suspect much code would transition quite quickly to the `|null` syntax, because to me it seems much easier to read, and there will certainly be tools to do it automatically. Yet the old syntax can coexist with the new "clearer" syntax, as both are easy to read within their use cases.

2019-09-04 22:49 UTC, cs278 commented on rfcs/0000-union-types-v2.md
> +$rt = new ReflectionFunction('test')->getReturnType();
```suggestion
$rt = (new ReflectionFunction('test'))->getReturnType();
```

2019-09-04 22:49 UTC, cs278 commented on rfcs/0000-union-types-v2.md
> +$rt2 = new ReflectionFunction('test')->getReturnType();
```suggestion
$rt2 = (new ReflectionFunction('test'))->getReturnType();
```

2019-09-05 05:32 UTC, mikeschinkel commented
I've posted this to the PHP internals mailing list already, but this is effectively an add-on proposal for this proposal:
 
- https://gist.github.com/mikeschinkel/50aec7094f5643223d28674639f9f117

As it's my first contribution to the PHP internals community I am hoping you will go gentle on me. :-)

2019-09-05 08:48 UTC, joshdifabio commented on rfcs/0000-union-types-v2.md
> +
> Fair enough. A bit weak, IMO, so if there isn't much complexity involved, I'd suggest introducing it to reduce the edge cases.

@mnapoli I noticed your downvote. Care to elaborate? (Personally, I value your opinion.)

2019-09-05 09:15 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +For example, if `A` and `B` are class aliases, then `A|B` remains a legal union type, even though it could be reduced to either `A` or `B`. Similarly, if `class B extends A {}`, then `A|B` is also a
I've clarified this in https://github.com/php/php-rfcs/pull/1/commits/1d13bf1210323496141f08b19c45e0aedbbc04d7. `use` is part of compile-time name resolution, so for our purposes, those `A` and `B` are the same ;)

2019-09-05 09:35 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +
In practice, what this means is that "php has a `false` type, but no `true` type" lands into the typical reasons to attack PHP upfront.

If introducing a `true` type has no technical nor BC burden, then adding it shouldn't be a problem, and a net value-add.

2019-09-05 09:39 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +
The `false` type is allowed here exclusively to support a very common legacy pattern. Expanding it beyond `false` IMHO should be done by making this a full feature, mentioned in the future scope as [literal types](https://github.com/nikic/php-rfcs/blob/union-types/rfcs/0000-union-types-v2.md#literal-types). With that, we could have `true`, `0` and `"foobar"` as "types" and be consistent in that sense.

However, unless we really go all the way in this fashion, I think that adding `true` adds neither value nor consistency to the proposal.

2019-09-05 10:10 UTC, msarca commented
@nikic I understand your point about global typedefs, but not about local alias types. I mean, we already use type aliases for functions, classes, constants, etc. every single day. The mechanism is there and is really frustrating for me (and maybe for others too) to understand why not going the extra mile and have at least local aliases. That's all.

2019-09-05 10:30 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +
Fair by me: I don't think we should stop this awesome RFC for this, and a `true` type may be added to a separate RFC (or a `false` type can be split out, if there's more tension caused by it)

2019-09-05 10:46 UTC, lisachenko commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
Ok, it's not about LSP, but we need to write class-dependent code and this considered as a bad smell. Ideally, there should be one single `ReflectionNamedType` or `ReflectionType` class, that is responsible for providing whole information about type. Otherwise we will have several similar classes with minor difference in implementation...

2019-09-05 11:01 UTC, oleg-andreyev commented
@msarca IMO doing an "extra mile" for core developers is going to be like 10x because of number of people involved in core :) We should be thankful to @nikic and others for pushing php forward to new level.

2019-09-05 11:46 UTC, Bigbear7 commented on rfcs/0000-union-types-v2.md
> +
I think that by not having true it's a bit confusing, at least for the PHP programmer not reading RFCs. Would introducing it now impact implementing it as a full feature later?

2019-09-05 11:51 UTC, hikari-no-yume commented on rfcs/0000-union-types-v2.md
> +
Don't some internal/extension objects (GMP maybe?) have special non-string casting behaviour? How do they fit in here?

2019-09-05 12:16 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +
Parameter parsing thankfully only supports implicit string casts. You can't pass a GMP object to an int parameter (in strict or weak mode).

2019-09-05 15:46 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +
As there seems to be a pretty strong consensus in favor of supporting `T|null`, I plan to change the RFC as follows:

 * `null` is supported as a type in unions. `T|null` is legal.
 * `null`, like `false`, is not supported as a singleton type. I believe supporting both `: null` and `: void` with their rather subtle difference in semantics would be catastrophically bad.
 * `?T` remains both supported and encouraged for the single-type case. It is not deprecated and there are no plans to deprecate it in the future.
 * `?(T1|T2)` syntax is not supported. If we allow `|null`, I see little point in having this. It might be supported in the future when parentheses in types become a thing in general.

2019-09-05 16:00 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +
@nikic I agree with all your points. Although I'm not opposed to `?(T1|T2)` syntax, some may even prefer it.

2019-09-05 16:03 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +
@nikic I agree with all your points. Although I'm not opposed to `?(T1|T2)` syntax, some may even prefer it.

2019-09-05 16:44 UTC, patrickallaert commented
@ocramius

> You're gonna get a NPE type-check error from any IDE or tool like @phpstan or @vimeo /psalm. 

Some languages (Rust, Kotlin, Julia, probably others) have solved the BDM (Billion Dollar Mistake)/NPE at their _design level_ already, without having to run an extra external tool.
If we have opportunities to design the languages to prevail from common errors without the use of external tools, we should consider it.

> The same type of error would happen even on something like:
> 
> ```php
> class A {}
> class B {
>     function something() : void {}
> }
> 
> function wrong(A|B $p) : void {
>     $p->something();
> }
> ```

Completely agree with your example. This is exactly the current problem we already have with `null`-able types:

```php
class B {
    function something() : void {}
}

function wrong(?B $p) : void {
    $p->something(); // Type of $p can either be null or B
}
```

If PHP would (it is just an example) emit a _Notice_ at run-time about type safety when it encounters a risky call, that would already partially solve the BDM:

```php
function wrong(?B $p) : void {
    $p->something(); // Type of $p can either be null or B
}

function right(?B $p) : void {
    // Type of $p is null or B
    if ($p instanceof B) {
        $p->something(); // Type of $p is B
    } else {
        // Type of $p is null
    }
}

wrong(new B); // Notice: Call to a member function something() on possibly nullable type "?B".
right(new B); // No notice, something() is called exclusively on type B
```

It would even be better at compile-time, but full type-inference is required in that case.

> It is not inherently an issue of `null`, but of type mismatch, which this RFC helps in detecting from a language PoV, while most responsible devs out there are adopting workarounds based on documentation and userland tools.

The BDM problem is not simply a type mismatch problem, otherwise it would not have existed in strictly typed languages. Fixing it, by design, is about making that run-time issue a compile-time one in order to embrace _correctness_.

For the sake of the demonstration (it is in no way as mature as this RFC), here is a proof of concept of "Options" in PHP somewhat inspired by [Rust's option](https://doc.rust-lang.org/std/option/index.html). Think about it like an enumeration of possible types. It handles a couple of things that this RFC is not targeting (and certainly the opposite):

- Provides a strong link between multiple possible types and the handling of those types with a certain degree of correctness: no missing type, no extra type. Also open the doors to detect, via type-inference, calls to invalid methods and/or `TypeError`s without external tools.
- If used for simple "nullable types" (`?Type`), provides an opportunity to tackle the BDM at compile-time.
- Makes it possible to evaluate the types in a specific custom order.

```php
<?php

class A {
    public function something() : self {
        return $this;
    }
}

class B {
    public function something() : self {
        return $this;
    }
}

class C {
    // Compared to A and B, returns null!
    public function something() : null {}
}

class D {
    public function noBCBreak(?A $p) : void {
        $p->something(); // Nothing special happens here, may still call "something()"
                         // on null, but #bc #joy #love
    }

    public function usingOptionForNullWithIf(Option(A|null) $p) : void {
        if ($p) {
            // $p can only be of type A in this scope
            $p->something();
        }
    }

    public function usingOptionForNullWithMatchCase(Option(A|null) $p) : void {
        match ($p) { // OK: All possible options are handled
            case A: $p->something();
            case null:
        }
    }

    public function nullNotHandled(Option(A|B|C|null) $p) : void {
        $p->something(); // Causes at compile time:
                         // PHP Fatal error: In Option(A|B|C|null), "null" does not
                         // implement a member function something().
    }

    public function nullHandled(Option(A|B|C|null) $p) : void {
        match ($p) { // OK: All possible options are handled
            case A|B|C:
                $p->something(); // OK: A, B and C all implement something()
            case null:
        }
    }

    public function notAllOptionsHandledWarning(Option(A|B|C|null) $p) : void {
        match ($p) { // Causes at compile time:
                     // PHP Notice: In Option(A|B|C|null), types C and null are not handled.
            case A|B:
                $p->something();
        }
    }

    public function unknownOptionHandledWarning(Option(A|B|C|null) $p) : void {
        match ($p) {
            case A|B|C:
                $p->something();
            case D: // Causes at compile time:
                    // PHP Notice: In Option(A|B|C|null), type D is not allowed.
            case null:
        }
    }

    public function nullValueReturnedNotHandled(Option(A|B|C|null) $p) : void {
        match ($p) { // OK: All possible options are handled
            case A|B|C:
                $p
                    ->something()  // OK: A, B and C all implement something()
                    ->something(); // Returned value of previous function is either:
                                   // A, B or null.
                                   // Causes at compile time:
                                   // PHP Fatal error: In Option(A|B|null), "null" does not
                                   // implement a member function something().
            case null:
        }
    }

    public function correct(Option(A|B|C|null) $p) : void {
        match ($p) { // OK: All possible options are handled
            case A|B|C:
                $value = $p->something() // OK: A, B and C all implement something()
                match ($value) { // Combining the returned values of (A|B|C)::something()
                                 // into an Option(A|B|null)
                    case A|B:
                        $value->something(); // OK: A and B all implement something()
                    case null:
                }
            case null:
        }
    }
}
```

2019-09-05 18:09 UTC, nikic commented
@patrickallaert I'm a big fan of algebraic datatypes and pattern patching, but those things are neither a replacement for union types, nor do they have anything but the most tenuous connection to this proposal. Once again, if you are interested in discussing this topic (and I do think it's a very interesting one!) please start a separate thread on the internals mailing list.

I will be marking comments that have no *direct* relation to union types as off-topic from this point on, to keep the conversation on track. There are a *lot* of tangents related to types and type systems we could discuss, but this is simply not the right place for them.

2019-09-05 18:16 UTC, Ocramius commented
@patrickallaert what you propose there is ADTs and function totality checking. What this PR/RFC proposes is:

 * Introduction of runtime assertions on union types that are already very widespread
 * Static information on union types
 * Reflection information on union types
 * Variance compile-time checks on union types

Yes, this causes an explosion of combinatory logic due to lack of genericised named union types (basically type classes), but that's something that is very much real and already part of the ecosystem. Static type-checking for completeness already exists in userland, and adding it to the engine is something I'd also love, but won't happen unless you can get internals to agree on it (and internal is very resistant to type soundness additions).

This patch is a massive step forward from the current state of reality, which has no type declarations ever for anything that is a union type, and userland relying on docblock comments instead.

2019-09-05 18:21 UTC, mnapoli commented on rfcs/0000-union-types-v2.md
> +
> @mnapoli I noticed your downvote. Care to elaborate?

@joshdifabio it's easier to simply downvote what you find on the internet rather than write a proper argument, I went with the lazy way 😄 

Nikita summed it up nicely already, I don't have a strong opinion on this and I don't think my opinion matters much here, but: `false` would exist for legacy reasons. `true` would have no real reason to exist except consistency, and I would favor aiming for what's essential over consistency or completeness.

2019-09-05 18:22 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
I see your point. The issue is that `ReflectionType` was just a naive assumption. With today's needs, it should've been an interface, implemented by `ReflectionNamedType` and extended by `ReflectionCompositeType` interface. `ReflectionCompositeType` would then be implemented by `ReflectionUnionType` and `ReflectionIntersectionType`.
Something like this:

```
                  <interface> ReflectionType
                          /           \         
                         /             \
       ReflectionNamedType     <interface> ReflectionCompositeType
                                            /   \
                                           /     \
                         ReflectionUnionType     ReflectionIntersectionType
```

2019-09-05 19:08 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
ReflectionType was indeed a naive assumption, which is why 7.1 added ReflectionNamedType specifically in preparation for future type-system extensions. As of PHP 8, ReflectionType is an abstract class, though we could also turn it into an interface -- it's just a question of shared implementation.

Having a class hierarchy is not a code smell -- trying to fit everything into a single class is the code smell. We are representing something akin to a (type) AST here, and doing that with a polymorphic object hierarchy is *the* standard way of going about it (in an OO language without ADTs).

Especially when you keep future type-system extensions like callable types with signatures in mind, it should be obvious that all of those different types cannot be part of the same interface without it turning into a convoluted API where some methods are only usable for some types.

2019-09-05 19:15 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
Because this probably never really came across when it was introduced, the way that `ReflectionNamedType` is *supposed* to be used is something like this...

```php
$type = $r->getType();
if ($type instanceof ReflectionNamedType) {
    // Use $type->getName() + $type->isBuiltin() here
} else if (...) {
    // Check more type kinds here in the future
} else {
    throw new Exception("Ooops, I don't understand this type!");
}
```

Of course, because `ReflectionNamedType` is the only `ReflectionType` right now, what people actually end up doing is just

```php
$type = $r->getType();
// Let's just assume that this is ReflectionNamedType!
// Use $type->getName() + $type->isBuiltin() here
```

which will of course break if new kinds of types are added in the future. (Though the previous variant will of course also break, just more gracefully.)

2019-09-05 19:22 UTC, theodorejb commented on rfcs/0000-union-types-v2.md
> +class ReflectionUnionType extends ReflectionType {
Given that `?T` is an alias of `T|null`, will a `ReflectionUnionType` instance be returned for all nullable types? Also, will the `getTypes()` method include `null`? If so, what will `allowsNull()` return for the `null` reflection type?

2019-09-05 19:41 UTC, mattacosta commented on rfcs/0000-union-types-v2.md
> +
@nikic While I agree with your first and third points, and have no preference on the fourth, I disagree with the second.

Unlike `false`, `null` is generally considered to be an actual type. While it may not see a lot of practical use by itself in declarations, it is still perfectly valid and there is no technical reason to prohibit it.

I would also disagree with the assessment that using `null` as a return type would be "catastrophic." It has been possible in other languages for a very long time with no ill effects. While subtle, there is still a difference that should remain expressible should the need ever arise. If its usage is to be discouraged, that should be done via linting rules instead.

2019-09-05 19:56 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +
The reason for prohibiting it is not technical, it's educational. The problem is not having `: null`, it's having both `: null` and `: void`, which would be very similar, but not quite the same (in terms of which `return`s are permitted). I know that some people would have preferred the former notation and I'm sure that some people are going to use it if it becomes available. While I have no problem with `?T` and `T|null` coexisting as aliases, I do have a problem with `: void` and `: null` coexisting (as non-aliases) in the ecosystem.

Do you have examples of languages that use both? The first few that come to mind (C, Java, Rust) don't (the first two only have void, the latter only has `()`). The closest example I can think of is C++ with `nullptr_t` and that one is rarely seen, mainly in a narrow use-case in method overloading.

2019-09-05 20:36 UTC, msarca commented on rfcs/0000-union-types-v2.md
> +
Honestly, it's not surprising that `null` is *generally* considered a type. The level of ignorance has reached alarming levels this days, especially with the rise of NodeJS.  The implicit return value for PHP functions is `null`. Adding a `null` pseudo-type would be somehow redundant. The only use case I can imagine is to use it as a return pseudo-type of an abstract method, just to force a child class to implement a non-empty method body.

2019-09-05 21:39 UTC, mattacosta commented on rfcs/0000-union-types-v2.md
> +### `false` pseudo-type
The problem with `false` is really one of meaning as opposed to technical requirement. With all the "standard" types, developers adopt a general definition of what they represent. The value `false` is generally defined similarly to:
```ts
// The two values of a logical condition.
enum Boolean {
  False,
  True,
}
```
As we can see, `false` was never meant to represent an error condition much in the same way that the string "apple" or the number 1234 don't generally represent error conditions either. Including `false` as a pseudo-type simply perpetuates this misrepresentation.

Furthermore, I would argue that may actually be detrimental to developers as its usage in this manner typically indicates an error.
- In the case of a function or method that should return a value, what was likely meant was `null` or another type similar to Rust's `Option<T>` or `Result<T, E>` which are meant to represent error conditions.
   This also covers literal types, because they are generally used to represent a subset of some other type. Since `true` is invalid in this context and `false` should not be combined with anything (its supertype does not have any other values), `false` can no longer represent its intended meaning, one of two values.
- In the case of a function or method that should not return a value, the correct result should actually be a thrown error instead. Using `false` in this second case is especially bad, as it may also prevent static analysis from narrowing the intended type.
```php
class Map {
  function has(key: T): bool {}
  function get(key: T): T | false {}
}

function foo(): T | null {
  $map = new Map();
  if ($map->has("bar")) {
    // Here we expect `get()` to always return `T`, however because of our poor
    // design decision to not throw an exception, the type cannot be narrowed,
    // and an error would be reported here because `T | false` != `T | null`.
    return $map->get("bar");
  }
  return null;
}
```

2019-09-05 22:21 UTC, mattacosta commented on rfcs/0000-union-types-v2.md
> +
Off the top of my head, TypeScript does.

The reason I like it remaining expressible is to enforce a narrow use-case.
```ts
abstract class A {
  abstract function foo(): T | null;
}

class B extends A {
  // In this class, this method should never return `T`.
  function foo(): null {
    // Do stuff...
    return null;
  }
}
```

That said, I'm not going to lose any sleep if the return type has to be `T | null` though. I'm just not entirely sold on this being the best place to be "educational," especially since it's safe and some of the languages you mentioned haven't exactly treated `null` as a first-class citizen in the past.

2019-09-06 00:45 UTC, mattacosta commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
This sounds a lot like you're treating `int|float` as a full on type (lets call it `IntFloat`), which is not what I would expect. Maybe I'm missing something, but if so, then I wouldn't even call this union strict typing as much as I would call it syntactic sugar for creating anonymous containers.

If that is the case, how about an alternative where `int|float` is treated more as a constraint, in that `int`, `float`, and `int|float` would all be valid, but all other types would produce an error?

2019-09-06 01:47 UTC, gocanto commented
I love this medium. I can learn so much just by reading `arguments`. Please, keep it up! @nikic

2019-09-06 04:45 UTC, mikeschinkel commented
Hi @nikic — Great work on this in general.

One area I am confused about is type safety regarding values that have been declared as a union parameter and then used elsewhere that requires a specific type. The following should illustrate:

```
function echoInt(int $intvar) {
   echo $intvar;
}
function showNumber(int|float $union) {
	echoInt($union);   // 
}
showNumber(1.23);
```

How can the developer explicitly specify that they want an `int` value to be passed to `echoInt()` when in `showNumber()` a `float` could be one of the two valid types? I know they can use `intval()`, but what if there is no type casting/conversion function available, such as with instances of classes? 

_(And I apologize in advance if I duplicate if you or someone has already addressed it here on this PR and I missed it while I was scanning the many comments on this page.)_

2019-09-06 05:30 UTC, KalleZ commented
@mikeschinkel When you enable `strict_types`, then even if you specify a `int`, a `float` is also allowed to be passed as they are compatible and is solved by a typecast. While this is an oddity at first, I do think this behavior should remain consistent. You can read more about this in details at the scalar types RFC:
https://wiki.php.net/rfc/scalar_type_hints_v5#integers_should_be_accepted_for_strict_float_arguments

2019-09-06 07:10 UTC, gocanto approved these changes

2019-09-06 07:13 UTC, brzuchal commented on rfcs/0000-union-types-v2.md
> +           | "object"
That one should be treated `object` type with some additional constraints. There is no value in `T|object` union type and that kind of union should be illegal. There is nothing wrong with `string|object` etc. union type as long as it's not combined with `T`. I think this was not raised before and deserves to be included and described.

2019-09-06 08:20 UTC, mikeschinkel commented
@KalleZ — Thank you for elaborating.  

But it leaves me with another question. What about the general case, illustrated using another albeit contrived example?:

```
class Guid {
	public $value = '';
	private $_instance;
	private function __construct() {}
	public static function instance() {}
}
function processGuid(Guid $guid) {
	echo $guid->value;
}
function useGuid(Guid|string $guid) {
	processGuid( $guid );
}
useGuid('9fb7f05e-5c15-42a7-8338-e1b3bb9311cc');
```

You might argue that `useGuild()` should look like this, but this will fail given `private function __construct()`:

```
function useGuidWillFail(Guid|string $guid) {
	if ( $guid instanceof Guid) {
		processGuid( $guid );
	} else {
		processGuid(new Guid($guid)); // Will fail because of private constructor
	}
}
```
I'd give you a better example but it's 3+ hours after my bedtime and the next 10 days are packed so not sure if I will have the time to reply later or not.

2019-09-06 08:46 UTC, IMSoP commented
@mikeschinkel Type declarations in PHP are simply assertions processed at runtime at specific points in time (when a function is called, when it returns, or when assigning to a property). It is up to the programmer (with the assistance of static analysers) to ensure that those assertions pass.

Adding union types wouldn't change that. If you write a function as accepting `string|Guid`, it's up to you to assure that a) the function is always called with one of those two types, and b) the function can actually handle both types without errors. If you don't have a way to safely handle strings, don't declare your function as accepting them.

2019-09-06 08:52 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
I'm not sure what you mean here. `int|float` is indeed a constraint, accepting values of type `int` and values of type `float`, and rejecting everything else; there is no such thing as "a value of type `int|float`".

2019-09-06 09:14 UTC, mikeschinkel commented
@IMSoP 

Thank you for your reply.

My interest here is:

1. To allow the programmer to explicitly specify types so readers of code can know their intent, and 
2. To empower static analyzers — and especially PhpStorm — to be able to accurately determine typing so a developer who wants to handle types without errors can leverage tools as much as possible.

So in the context of your reply my question can be phrased as:

>  _"How can we ensure that it is possible to specify types explicitly to convey intent?"_

-Mike

P.S. Another way to look at this is:

> _"Ideally we should be able to formulate proofs about the behaviour of a program; it is about knowing, without executing any code, that certain states are impossible. We should be able to say 'this is always an int,' for example. This is especially of concern because objects in PHP they can never be cast, even explicitly. It seems like we need a 'container' to hold a union types values; one given a name and a meaning by the programmer and  'type constraints' which determines which values are expected, i.e. can be assigned to that container."_

P.P.S. I stole that second quote from [here](http://rwec.co.uk/blog/2016/10/towards-a-consistent-php-type-checking-system/). 

P.P.P.S. As you and others may not know me I'll mention I've been programming professionally in PHP since 2006. I've also been a PhpStorm user since < 1.0 and submitted over 150+ bug reports and feature requests too. I say this so that anyone who replies to me can assume I am indeed familiar with programming in PHP.

2019-09-06 09:23 UTC, IMSoP commented
@mikeschinkel Then I don't understand your question, or your example. A static analyser will be able to point out that your `useGuid` function is incorrect, because it will pass a string to a function that doesn't accept strings. How you fix that is up to you - you could write `if ( is_string($guid) ) { echo 'Hooray!'; }`, or `if ( is_string($guid) ) { launchNuclearWeapons(); }`, or simply `if ( ! is_string($guid) ) { processGuid( $guid ); }`. A type system can't enforce that you do something _useful_ with every type, only that you won't generate any type mismatches.

2019-09-06 09:29 UTC, mikeschinkel commented
@IMSoP Looks like I am going to have to go do some coding and come across the real world examples because my attempts to generate a contrived example is not getting the point across. Hope I can do so because the concern becomes moot. 
That and I'm not 5 hours past when I should have been in bed. :-( Night.

2019-09-06 11:48 UTC, Danack commented on rfcs/0000-union-types-v2.md
> +           | "object"
"There is no value in T|object union type and that kind of union should be illegal."
 
 How does it follow that there being no value leads to that type of union needed to be illegal?
 
 Are we going to enforce that for other 'duplicate' types?
 
```
 class A {}
 
 class B extends A{
   // doesn't define any extra methods
 } 
  
 // Is this going to be illegal?
 foo(A|B $x) {...} 
```

This sound like something that could and should be left to static code analyzer's rather than being enforced by the engine.

2019-09-06 12:08 UTC, brzuchal commented on rfcs/0000-union-types-v2.md
> +           | "object"
At the end `A|B` union resolves to two classes, but in comparison to `A|object` IMO it could lead to misunderstanding, cause `object` would widen the typehint and when combined with `A` doesn't change anything, the `object` typehint would still accept all objects so it's not narrowing anything. 
In my mind, it's different than `A|B` union cause a value of it would be resolved on run-time and unlike `A|object` which can be indicated on compile-time.

2019-09-06 13:18 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +           | "object"
I've added the `object` case to the "duplicate types" section: https://github.com/php/php-rfcs/pull/1/commits/698cbd3d18d0c887eb680df1e2d1a4b8988b36b8

2019-09-06 13:20 UTC, Danack commented on rfcs/0000-union-types-v2.md
> +           | "object"
"it could lead to misunderstanding", "unlike A|object which can be indicated on compile-time."

Both those things sound like it disallowing in a code inspection tool, rather than the engine, would be the better choice.

btw I can imagine some some scenarios where I'm refactoring code, and temporarily a type signature might need to be A|object for a short period of time, while the refactoring is being done.  If it wasn't possible to define that type at all, it would mean needing to remove the A part temporarily, which would make refactoring be more difficult.

2019-09-06 13:30 UTC, claudepache commented on rfcs/0000-union-types-v2.md
> +  * If `object` is used, class types cannot be used additionally.
There is also `array|iterable`.

2019-09-06 13:44 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +
Proposal updated to use `|null` notation in https://github.com/php/php-rfcs/pull/1/commits/0a2782bd1293c6e669b2c35df38fec354d42c949.

2019-09-06 13:45 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +    | "?" "(" union_type ")"
Proposal updated to use `|null` notation in https://github.com/php/php-rfcs/pull/1/commits/0a2782bd1293c6e669b2c35df38fec354d42c949.

2019-09-06 13:58 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +
Table added in https://github.com/php/php-rfcs/pull/1/commits/931afdd6af4144a1ef815835af04362d44fdf0c1. Thanks!

2019-09-06 14:14 UTC, brzuchal approved these changes

2019-09-06 14:28 UTC, muglug approved these changes

2019-09-06 15:07 UTC, mattacosta commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
I'll admit, I did not explain that well (or really at all) now that I've re-read it. Let's try this again...

The way I'm reading this is, with respect to function signatures and code analysis:
- In coercive mode, we have `T` which does not equal `int|float` but can be converted to one of the types, and `int` which does not equal `int|float` but does not need a conversion to match a type.
- In strict mode, we have `int|float` must equal `int|float`? Otherwise how could `int` not work with `int|float`? <-- Did my brain take a wrong turn here?

2019-09-06 15:10 UTC, bwoebi commented on rfcs/0000-union-types-v2.md
> +  * If `object` is used, class types cannot be used additionally.
and `Traversable|iterable` as well

2019-09-06 15:14 UTC, bwoebi commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
I would not restrict these; in particular a child class method may always return the given type. (e.g. the parent class returns `Foo|null`, but the child class will never return a `Foo` (e.g. null object), only `null` for that method, ever).

2019-09-06 15:25 UTC, Ocramius commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
```php
function caller(int $v) : void
{
    callee($v);
}

function callee(int|float $v) : void
{
    var_dump($v);
}
```

This is valid both in strict and non-strict mode. The idea is that your value must fit in the type assertion performed **at runtime**.

2019-09-06 15:42 UTC, derrabus commented on rfcs/0000-union-types-v2.md
> + * A union `U_1|...|U_n` is a subtype of `V_1|...|V_n` if for each `U_i` there exists a `V_j` such that `U_i` is a subtype of `V_j`.
```suggestion
 * A union `U_1|...|U_n` is a subtype of `V_1|...|V_m` if for each `U_i` there exists a `V_j` such that `U_i` is a subtype of `V_j`.
```

The two union sets can differ in the number of elements:

* Covariance should allow me to drop types from a union. For instance, if a method has the return type `SomeClass|SomeOtherClass`, a child class should be allowed to be declared with a return type `SomeClass` or even with a subtype of `ChildClass`. Currently, php already allows to drop `null` from the union (parent method has `?SomeClass` as return type, child method has `SomeClass`).
* Covariance should also allow me to replace a type by multiple subtypes, e.g. change the return type `SomeInterface` to `SomeImplementation|SomeOtherImplementation`, if both classes implement `SomeInterface`.

2019-09-06 15:44 UTC, claudepache commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
The big issue of having both `null` and `void` as return type, is that several people will choose one or the other based on non-technical, non-semantic rationale. Pragmatically, I’m not sure that the advantage of having a standalone `null` type trumps the problems that will arise from having both `null` and `void`.

2019-09-06 15:48 UTC, mattacosta commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
That's exactly what I would expect, but then how is the variance model breaking here?

2019-09-06 15:48 UTC, derrabus commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
> The big issue of having both `null` and `void` as return type, is that several people will choose one or the other based on non-technical, non-semantic rationale.

`void` is already treated differently by the compiler. You cannot do `return null;` in a method with a `void` return type and you cannot do `return;` in a method with a `?SomeClass` return type.

2019-09-06 15:54 UTC, rob006 commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
Lack of standalone `null`, `false` or `true` is artificial limitation, based on arbitrary decision. It is just unnatural that you can't narrow return type from `string|null` to `null` or from `string|false` to `false`. Confusing `null` and `void` may be a problem, but such inconsistency in return type covariance may be even worse.

2019-09-06 15:56 UTC, derrabus commented on rfcs/0000-union-types-v2.md
> +Of course, the same can also be done with multiple union members at a time, and be combined with the addition/removal of types mentioned previously.
As mentioned above, types could also fan out into multiple types and merge into a common supertype:

```
```php
interface C {}
class A implements C {}
class B implements C {}

class Test {
    public function param1(A|B $param) {}
    public function return1(): C {}
}
class Test2 extends Test {
    public function param1(C $param) {} // Allowed: Method still accepts instances of A and B.
    public function return1(): A|B {}   // Allowed: Method still guarantees to return instances of C.
}
```

2019-09-06 16:18 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +Of course, the same can also be done with multiple union members at a time, and be combined with the addition/removal of types mentioned previously.
Yes, this is what the "combined with" wording gets at, but I don't think we need the extra example. The technical definition above captures this, and the examples are there just to provide an intuition.

2019-09-06 16:29 UTC, derrabus commented on rfcs/0000-union-types-v2.md
> +Of course, the same can also be done with multiple union members at a time, and be combined with the addition/removal of types mentioned previously.
All right.

2019-09-06 16:31 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
I would be more amenable to this argument is someone could provide an example where this would be useful. Even in cases where only null/false is possible from an implementation perspective, I would generally expect the type to remain `?T` from a semantic perspective.

Specifically, the example needs to not just have a `: null` type, but consuming code also needs to specifically rely on that being the case.

2019-09-06 16:42 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
Sorry, the statement here was technically not quite correct, fixed in https://github.com/php/php-rfcs/pull/1/commits/3622f8c58229c0c9c290f9921f830dafa56d07fd. Was that the confusion?

If not, to establish the baseline of what we're discussing:

 * We're in weak mode.
 * We have an `float` type that per current weak-typing semantics allows all booleans, integers, floats and numeric strings.
 * We have a `int|float` type under an alternative proposal where *only* exactly integers and floats are allowed. This means it accepts strictly less inputs than `int`, because booleans and numeric strings are no longer allowed.

Given this, you can no longer go, during inheritance, from `foo(): int|float` to `foo(): int`, because this would actually widen the return type in weak mode. The reverse also cannot be allowed, because this still does narrow in strict mode.

To have any reasonable notion of variance, weak mode for single types and weak mode for union types need to behave consistently, which is why this alternative is not possible.

2019-09-06 16:50 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
The following is legal in weak mode:
```
class A { function foo(int $a) {} }
$x = new A;
$x->foo('42'); // coerced to int, passes constraint
```

With union types, you should logically be allowed to expand the accepted types in a sub-class:

```
class B extends A { function foo(int|float $a) {} }
```

If using a union type automatically triggered strict typing for that parameter (i.e. they never attempted to cast the input value), then the following would be an error even in weak mode:
```
$x = new B; // remember this is a sub-type of A, so should be interchangeable
$x->foo('42'); // doesn't satisfy constraint without coercion
```

I believe that's what Nikita means when he says that making union types always strict would "break the variance model". Therefore we need to define some logic for automatic casts when a union type is checked in weak mode.

2019-09-06 16:56 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +  * If `object` is used, class types cannot be used additionally.
Added in https://github.com/php/php-rfcs/pull/1/commits/edcc2df3fb9bcb676c742d626e1e1600ab92c634.

2019-09-06 17:34 UTC, rob006 commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
@nikic You may get such a situation with any kind of fake data provider. For example you can have `Cache` with `get($id): CacheResult|string|null`, `StringCache extends Cache` with `get($id): string` and `FakeCache extends Cache` which never returns result, always `null`, so it should be `get($id): null`. Returning `null` is part of the interface of `FakeCache` - this component should never return a real result (that is the point of `FakeCache`), while still should be an instance of `Cache`. It may be surprising and annoying that you can't do that and can't have something like:

```php
public function fetchFromCache(StringCache|FakeCache $cache): string {
    return $this->parse($cache->get(self::CACHE_ID));
}

public abstract parse(?string $data): string;
```

It may not look like a real-world example, but at PHP scale you will get thousands of similar situations and people will waste thousands of hours trying to debug this and discuss why in PHP covariance works only in 99% cases. "Someone decided that having `null` as standalone type may be too confusing" may not be a satisfying answer for them.

2019-09-06 20:12 UTC, bwoebi commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
@nikic Not necessarily. it is also useful for static analysis. If there are only two candidate classes an object contained in a variable `$a` is, one of them has a method `foo()` returning `null`, the other class' `foo()` returns `Foo|null`:
```
if ($a->foo()) {
    // here we can be certain that $a is the class whose foo() returns Foo|null
}
```

This can then, in future, also be used by e.g. opcache/JIT (with whole-program analysis) to restrict the set of possible classes there, and if equal to 1, optimize method calls directly.

2019-09-06 20:37 UTC, Crell commented on rfcs/0000-union-types-v2.md
> +
The logic here is sound; my one concern is that allowing false as an explicit return type seems to indicate that it's an OK/good thing to do.  I think most agree these days that returning `something|false` is bad design, but PHP (and sadly much of userspace) is full of that bad design.

Is there some way, perhaps just in documentation, that we could call out that returning `foo|false` is supported but a bad idea?  Or at least avoid giving the implication that it's a good idea?

2019-09-06 21:19 UTC, mattacosta commented on rfcs/0000-union-types-v2.md
> +The first is to specify that union types *always* use strict typing, thus avoiding any complicated coercion semantics altogether. Apart from the inconsistency this introduces in the language, this ha
@nikic @IMSoP Yes, this clears everything up nicely. I was trying to come up with a really weird set of rules that would satisfy all the conditions of what you said, and along with a faulty assumption it was wrecking my brain.

2019-09-07 10:20 UTC, dgafka commented
Does this RFC takes under consideration possibility to introduce scalar types as classes in future?   

```php
function(int|string $data) 
->
function(Integer|String $data)
```

Will this still be valid, considering above classes can have different methods?

2019-09-07 12:54 UTC, kelunik commented on rfcs/0000-union-types-v2.md
> +
I think people should just fall back to `Foo|bool` for now.

2019-09-07 16:29 UTC, claudepache commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
The arguments of the two previous comments are not related to union types (that is, their validity does not depend on the existence of union types), and the demand for standalone `false` and `null` seems to be more a consequence of the chosen syntax for falsable/nullable types rather than of a real need (although they certainly do have some limited usefulness). Whether `false` and `null` should be accepted as standalone types rather than just auxiliary values is an interesting question, but I think it is orthogonal to the Union Types RFC.

The intent of the RFC would be more clear if the grammar did not incorporate the `null` and `false` tokens into `simple_type`:

```
type: void_type
    | simple_type
    | "?" simple_type
    | union_type
    ;

union_type: simple_type "|" simple_type
          | simple_type "|" auxiliary_value
          | ( auxiliary_value "|" )+ simple_type
          | union_type "|" simple_type
          | union_type "|" auxiliary_value
          ;

void_type: "void"
         ;

simple_type: "bool"
           | "int"
           | "float"
           | "string"
           | "array"
           | "object"
           | "iterable"
           | "callable"       # not legal in property types
           | "self"
           | "parent"
           | namespaced_name
           ;

auxiliary_value: "false" 
               | "null" 
               ;
```

Incidentally, the grammar above removes the support of `false|null`, as it was probably not intended to be supported.

2019-09-07 16:35 UTC, IMSoP commented
@dgafka That would be no different from any other union type; you could write `Logger|HTTPClient` or `string|HTTPResponse`; it would be up to you what you actually did with that value. The type declaration doesn't tell the language to make your code work with those types; it tells the language that _you_ have made your code work with those types.

2019-09-07 16:56 UTC, rob006 commented on rfcs/0000-union-types-v2.md
> +           | "null"           # only legal in unions
> Whether `false` and `null` should be accepted as standalone types rather than just auxiliary values is an interesting question, but I think it is orthogonal to the Union Types RFC.

This RFC  defines special exceptions for `false` and `null`, so they're treated differently than any other type. If deciding whether standalone `false` and `null` should be allowed is outside of scope of this RFC, then it should not create any special rules for them and follow standard covariance rules.

2019-09-07 17:01 UTC, claudepache commented on rfcs/0000-union-types-v2.md
> +
Especially now that the syntax for nullable type has switched to `T|null`, it should be made clear that not only `false`, but also both `?false` and `false|null`, are unsupported.

2019-09-07 23:32 UTC, noobshow commented
> Proposal for the addition of union types `T1|T2|...`. There has been a [previous proposal](https://wiki.php.net/rfc/union_types) on this topic, which has been declined.
> 
> [**Rendered Proposal**](https://github.com/nikic/php-rfcs/blob/union-types/rfcs/0000-union-types-v2.md)

Is there a detail we could know about how this rfc handles precedence between `int|float` union type and one thing I think should be clear is that will unlimited amount of union types be allowed as seen in some of these examples(which in my opinion is ugly) or there will be a kind of maximum restriction on what to use, possible 2 to 3 union type limit?

2019-09-08 03:53 UTC, marcospassos commented on rfcs/0000-union-types-v2.md
> +
Adding support for `false` in favor of `bool` without proper support for literal types helps to promote bad design decisions

2019-09-08 15:55 UTC, foobar13373 commented
This RFC is a nice step, bit I'd rather have truly templated functions, like C++ has.

```
function sum(T $a, T $b): T
{
    return $a + $b;
}
```

If called with two `int`s it returns int, if called with two `float`s it retruns `float`. If called with anything else it throws a type error (including calling it with one `int `and one `float`).

Side note: this would be the first step of introducing operator overloading. So that we can define what, for example, `+` does for instances of own classes. If you want an example: just think of a class `Vector` that overloads the `+` so that you can just say `new Vector(1,2) + new Vector(3,1)` (which would give a vector instance of `(4,3)` if in cartesian space). If this would be possible you can imagine all kinds of templated methods that would auto-invoke the correct operator functions if `T` implements it.

2019-09-08 16:07 UTC, muglug commented
> This RFC is a nice step, bit I'd rather have truly templated functions, like C++ has.

I believe this is very far off-topic (and the example you give does not behave similarly in Hack, a language that _does_ have templated functions).

2019-09-08 16:48 UTC, IMSoP commented
@noobshow 
> Is there a detail we could know about how this rfc handles precedence between `int|float` union type 

Do you mean the precedence when coercing, e.g. which of `int` or `float` will be received when a function requiring `int|float` is given a `string` value in weak typing mode? If so, see [this section of the RFC](https://github.com/nikic/php-rfcs/blob/union-types/rfcs/0000-union-types-v2.md#coercive-typing-mode).

> one thing I think should be clear is that will unlimited amount of union types be allowed as seen in some of these examples(which in my opinion is ugly) or there will be a kind of maximum restriction on what to use, possibly 2 to 3 union type limit?

I don't see any particular need to enforce a limit on this. It would indeed by ugly to have 10 types listed in a function signature, but only in the same way that it's ugly to have 10 parameters to a function, and the language doesn't stop you doing that. I think such limits should be left to coding conventions on a given project, where the limit can be more flexible if circumstances demand.

2019-09-08 18:03 UTC, mikeschinkel commented
> @IMSoP  _"The type declaration doesn't tell the language to make your code work with those types; it tells the language that _you_ have made your code work with those types."_

Your statement can be read in a manner than implies the runtime does nothing with typehints, but that is not the case. See the following code:

```
<?php
declare(strict_types=1);
class Foo{}
function foo(Foo $foo) {}
foo(1);
```
...throw the following error messages, and return an HTTP `500` when used in a web page:
```
[08-Sep-2019 17:54:36] WARNING: "NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to foo() must be an instance of Foo, integer given, called in /var/www/test.php on line 5 and defined in /var/www/test.php:4"
[08-Sep-2019 17:54:36] WARNING: "Stack trace:"
[08-Sep-2019 17:54:36] WARNING: "#0 /var/www/test.php(5): foo(1)"
[08-Sep-2019 17:54:36] WARNING: "#1 {main}"
[08-Sep-2019 17:54:36] WARNING: "  thrown in /var/www/test.php on line 4"
```
The point being that type hints are more than just documentation, they can control the behavior of the PHP runtime.

_(And I would say this is not off-topic because we are discussion type hint behavior that union types will also adopt.)_

2019-09-08 18:41 UTC, IMSoP commented
@mikeschinkel 
> Your statement can be read in a manner than implies the runtime does nothing with typehints, but that is not the case.

I didn't mean to imply that the type declarations don't do anything. What I meant was that they don't make code work which otherwise doesn't work. If you write this:

```
class Foo { public function methodOnFoo(); }
class Bar { public function methodOnBar(); }
function doSomething(Foo $foo) { $foo->methodOnBar(); }
doSomething(new Foo);
```

Then your code has a bug, because it's calling the wrong method. Union types don't change that fact. It means you can now write this:

```
function doSomething(Foo|Bar $fooOrBar) { $fooOrBar->methodOnBar(); }
doSomething(new Foo);
```

But you still have the same bug; saying that your function now accepts both `Foo` and `Bar` instances doesn't change the fact that `$foo` doesn't have a method called `methodOnBar`. However, you can also write this:

```
function doSomething(Foo|Bar $fooOrBar) { if ( $fooOrBar instanceOf Bar ) { $fooOrBar->methodOnBar(); } }
doSomething(new Foo);
```

This code no longer has a bug, because you have actually handled the possibility of being passed a `Foo` instead of a `Bar`. That's what I meant by "telling the language that you have made your code work with those types".

2019-09-08 20:04 UTC, dgafka commented
```php
function doSomething(Foo|Bar $fooOrBar) { $fooOrBar->execute(); }
doSomething(new Foo);
```

@IMSoP This leads to the situation, when objects, that have nothing in common, can coexists together. We all make mistakes from time to time, if this will be treated as expected behaviour (not throwing exception, because of incompatibility), we won't be able to receive any feedback as long as this method is not executed

```php
function doSomething(Foo|float $fooOrBar) { $fooOrBar->execute(); }
doSomething(new Foo);
```
Sorry, but I can't find example like this in RFC. Will this code compile?
If not, what is the difference between the first example and this one?

2019-09-08 21:52 UTC, IMSoP commented
@dgafka 
> ```
> function doSomething(Foo|float $fooOrBar) { $fooOrBar->execute(); }
> doSomething(new Foo);
> ```
> 
> Sorry, but I can't find example like this in RFC. Will this code compile?

Firstly, none of the errors we are talking about here are at compile time. All type-checking in PHP happens at run-time, whether that's checking that a value matches a declared parameter type, or checking that a value has a required method.

Secondly, let's take a step back and consider a function _without any_ type declarations:

```
function doSomething($x) { $x->execute(); }
doSomething(new Foo); // will error if Foo does not have a method called "execute"
doSomething(1.5); // will always error, because you can't call any method on a float
```

Adding type declarations doesn't change that:

```
function doSomething2(Foo $x) { $x->execute(); }
doSomething2(new Foo); // will still error if Foo has no "execute" method
doSomething2(1.5); // will give a different error, because the type check fails

function doSomething3(float $x) { $x->execute(); }
doSomething3(new Foo); // will always error, because the type check fails
doSomething3(1.5); // will still error, because you still can't call a method on a float

function doSomething4(float|Foo $x) { $x->execute(); }
doSomething4(new Foo); // as before, will error if Foo has no "execute" method
doSomething4(1.5); // yes, it is still an error to call a method on a float
```

Union types aren't going to make your wrong code become right. What they will do, is if you have some reason to write a function which _can_ safely handle both `float` and `Foo` as input, you can tell PHP that; PHP will then allow both those types, but throw an Error if the value you pass at runtime is a `Bar`, or a `boolean`, or `null`. Ultimately, it's just short-hand for writing `assert(is_float($x) || $x instanceof Foo);` at the top of your function; writing the rest of the function is up to you.

2019-09-08 22:43 UTC, mikeschinkel commented
@IMSoP
Okay, I think I now get what you were originally trying to convey. But since this is starting to get a bit off-topic though nothing to generate a PR for, I'll hide my response from the conversation: 
<details>
<summary>Off-topic</summary>

Knowing that Type Errors are thrown in strict mode caused me to be unclear what you meant.  Maybe because anyone who has used PHP for any length of time knows that almost nothing in PHP enforces code to be correct, it is always up to the developer so it seemed a rather too-obvious point to make.

OTOH, for someone who does not use PHP a lot — and I don't mean  me —  it would seem counter-intuitive that PHP would throw error for some misuse but not others _(It feels like this is an incomplete aspect of PHP's strict mode.)_ But I guess if someone considers the dynamic nature of PHP, maybe its is not so non-obvious.

Still, your emphasis on the point ignores an important practical concern. Even though PHP does not tell me that the method is not valid until it runs the code, PhpStorm and I assume other static analyzers **do** tell us when method calls are invalid, and I would expect the same to be possible for union types.

You emphasized your point at least twice, once to me directly, so given the fact that other tools _can_ benefit from more detailed typing information, I do not understand why the fact that PHP itself does not protect your against a certain class of bad code when tools can is really relaxant to emphasize?
</details>

2019-09-09 05:44 UTC, dgafka commented
@IMSoP Thanks for your detailed answers.

I think I didn't explained myself enough.  
```php
class Foo {
   public function execute(int $amount) : int;
}

class Bar {
   public function execute() : void;
}

function doSomething(Foo|Bar $fooOrBar) { $fooOrBar->execute(); }
doSomething(new Foo);
```

As those classes have nothing in common we may expect, that they can be incompatible now or in future (what is the problem, to change method declaration, we are not bind to any specific interface? :) ).  
This could result in the same exception during compile time as

```php
interface FooBarInterface {
	public function execute() : void;
}

class Foo implements FooBarInterface {
   public function execute(int $amount) : int;
}

class Bar  implements FooBarInterface  {
   public function execute() : void;
}

Fatal Error: Declaration of Foo::execute(int $amount): int must be compatible with FooBarInterface::execute(): void
```
This leads us to code, that has correct declarations all the time. Pick one class or typehint for interface.  

I understand that this limit the usage of unions. In fact the scope of unions would focus on scalar types mostly in that case. 
The second problem is it will decrease flexibility. The language will prevent from introduction possible bug to your codebase, even if you exactly know what you're doing.  

I think the question in here, how much flexibility and responsibility can be put on developers?  
I've mixed feelings about this one.

2019-09-09 06:43 UTC, foobar13372 commented
What about introducing typed collections first? So that we can have `array(string)` or `array(MyClass)` or `new MyTraversable<MyClass>`.

2019-09-09 07:05 UTC, brzuchal commented
@foobar13372 this for sure is out of the scope of discussed RFC.

2019-09-09 08:47 UTC, IMSoP commented
@mikeschinkel @dgafka  Type declarations in PHP do not change what methods you can call. `strict_types` doesn't change that (it doesn't affect objects at all), and union types won't change that either.

Static analysis tools can indeed detect all the errors in my last comment, _and already do_ based on docblock annotations. But there is no official static analyser for PHP, only runtime checks. Union types won't change that, either.

Finally, there is no reason to ban unions of incompatible types; the following code is perfectly valid; a static analyser can prove that it's valid, and the PHP runtime will not generate any errors.

```
class A { function setup() {} function doA() {} }
class B { function setup() {} function doB() [} }

// Using a union type when you're only using a method you know both classes have
function foo(A|B $x) {
   $x->setup();
}

// Using a union type when you're going to handle the cases separately
function bar(A|B $x) {
   // more logic here
   if ( $x instanceof A ) { 
       $x->doA(); 
   }
   else {
       $x->doB();
   }
   // more logic here
}
```

2019-09-09 10:20 UTC, IMSoP commented on rfcs/0000-union-types-v2.md
> +    public A|B $prop;
I can see there would be some value if the language was able to point this out, but there's plenty of ways of writing redundant code, so I don't see it as a "limitation" particularly. For instance, you can already write `if ( $x instanceof A || $x instanceof B )`, or even `if ( $x instanceof A || $x instanceof A )`, which is clearly redundant. A tool like PHPStan may well spot this for you, and can probably spot redundant union types as well, because it can analyse your whole project.

2019-09-09 15:52 UTC, theodorejb commented on rfcs/0000-union-types-v2.md
> +At this point in time, parentheses in types are only allowed in the one case where they are necessary, which is the `?(T1|T2|...)` syntax. With further extensions to the type system (such as intersec
It seems that this paragraph is no longer applicable now that the `T1|T2|null` syntax is used.

2019-09-10 01:23 UTC, betrayerx commented
Верните обычный не-типизированный РНР 5!!!

2019-09-11 17:23 UTC, TysonAndre commented
I don't see any major issues or missing functionality with this rfc

- `Throwable` is one special case to consider that I didn't see brought up in discussion, but using it in param/return types is really infrequent. It could be equivalent to `Error|Exception` for class inheritance checks (similar to `iterable`)?

  Background: Trying to implement `Throwable` in user classes causes `Class Xyz cannot implement interface Throwable, extend Exception or Error`
- I agree with earlier comments mentioning that this should specify that `false|null` is forbidden https://github.com/php/php-rfcs/pull/1#discussion_r321976308
- Out of scope because it can&should be dealt with later: Some syntax on `Type Aliases` might have an impact on the cast syntax, for code such as `use A|false as C; $x = (C)$value;`

  EDIT: and code such as `use A|B|float as C; $x = new C(); C::static_method();`

2019-09-11 17:40 UTC, TysonAndre commented on rfcs/0000-union-types-v2.md
> +""      --> false     // not numeric string, fall back to bool
I don't see an explicit specification of what this does for casting to union types containing `false`, e.g. `int|float|false`.

My preference would that `"X" -> int|float|false` would become a thrown `TypeError`, and "" would become `false`

If that was the intended behavior, the above section should also be amended to something along the below lines:

```diff
- 4. `bool`
+ 4. `bool` (or `false` if the `false` is in the union type and the value would be false when cast to `bool`)
```

2019-09-11 18:05 UTC, deleugpn approved these changes

2019-09-11 20:19 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +""      --> false     // not numeric string, fall back to bool
The behavior for `false` is current as specified by omission, but should be explicitly mentioned: All types that are not explicitly listed here are not eligible target types for implicit coercions. This includes `null`, `false`, class types types, etc. In other words, the only valid value for the `false` type is `false`.

Given the intended use, I don't believe that there is any use-case for an implicit coercion to `false` (it is essentially used as an alternative `null` for legacy reasons and `null` is never subject to coercions either). We may wish to revisit this question if/when we introduce literal types and define general coercion semantics (or possibly non-coercion semantics...) at that point. For now restricting it to non-coercing is the conservative choice.

This is also one more point in favor of not supporting a `true` type at this point in time. That would bring up the question of how `true|false` relates to `bool` and whether those types are considered equal. If they are, this would essentially force the coercion semantics you suggest on the `true` and `false` literal types. That's certainly a possibility, but not necessary what we actually want, especially when it comes to the pseudo-enum use-case (e.g. if you have ` type Weekday = 1|2|3|4|5|6|7`, should this *really* accept `true` as a value because that happens to coerce to `1`?)

2019-09-11 20:25 UTC, nikic commented
> I don't see any major issues or missing functionality with this rfc
> 
>     * `Throwable` is one special case to consider that I didn't see brought up in discussion, but using it in param/return types is really infrequent. It could be equivalent to `Error|Exception` for class inheritance checks (similar to `iterable`)?
>       Background: Trying to implement `Throwable` in user classes causes `Class Xyz cannot implement interface Throwable, extend Exception or Error`

Interesting point. I think that until PHP has a first-class notion that exposes this fact on a language level, `Throwable` should receive no special treatment (`DateTimeInterface` is another example). E.g. Kotlin has a concept of [sealed classes](https://kotlinlang.org/docs/reference/sealed-classes.html) that could expose this on the type system level.

>     * Out of scope because it can&should be dealt with later: Some syntax on `Type Aliases` might have an impact on the cast syntax, for code such as `use A|false as C; $x = (C)$value;`
>       EDIT: and code such as `use A|B|float as C; $x = new C(); C::static_method();`

I don't really understand what your concern here is. I'd expect that the latter two examples would give you a compile-error along the lines of "trying to use a type (alias) where a class is expected".

2019-09-12 03:39 UTC, mattacosta commented
Just out of curiosity, would it be possible to only permit `false` in internal functions?

This is essentially what I do in my code analysis project. Only stubs flagged as containing internal functions can use `false` in their type hints. This allows their return values to be narrowed more easily, while also preventing misuse in actual code.

2019-09-12 08:04 UTC, claudepache commented
> Just out of curiosity, would it be possible to only permit `false` in internal functions?

I don’t think that it is a good idea. People may (and do) write (or have written) functions that follows the same pattern as existing internal functions. Whether it is should be done, is a question of coding standard. Of course, returning `false` is a legacy convention, it does not mean that it is a bad convention (objectively: my code would not have been better if `strpos()` returned `null` or `NAN` or `-1` instead of `false`) that must be forbidden at language level.

2019-09-12 08:15 UTC, claudepache commented
If it is deemed valuable to put restrictions on use of `false`, it seems reasonable to me to restrict `false` to _return_ types.

2019-09-12 08:20 UTC, nikic commented
To both

> Just out of curiosity, would it be possible to only permit `false` in internal functions?
> 
> This is essentially what I do in my code analysis project. Only stubs flagged as containing internal functions can use `false` in their type hints. This allows their return values to be narrowed more easily, while also preventing misuse in actual code.

and

> If it is deemed valuable to put restrictions on use of `false`, it seems reasonable to me to restrict `false` to _return_ types.

I don't think the use of `false` should be restricted in either way. Code still has to interface with internal functions (which make heavy use of this pattern), and this code would likely have `T|false` style unions. E.g. if you have `strpos` returning `int|false`, you might pass the value on to a `int|false $pos` argument. Of course, you *could* remap the types via `$pos === false ? null : $pos` and arrive at a more pure `?int $pos` type, but I'm not sure who benefits from that, especially for private/internal code.

2019-09-12 09:34 UTC, mattacosta commented
> E.g. if you have `strpos` returning `int|false`, you might pass the value on to a `int|false $pos` argument. Of course, you _could_ remap the types via `$pos === false ? null : $pos` and arrive at a more pure `?int $pos` type, but I'm not sure who benefits from that, especially for private/internal code.

In practice however, whenever that happens it's usually in the context of:
```php
if ($pos === FALSE) {
  return;
}
// or
if ($pos === FALSE) {
  throw new Exception();
}
```
...so it wouldn't make it very far. Additionally, if the value does get returned or passed to another function, that return type or parameter would be typed as `T|bool`, so there's no need to convert to `T|null`.

2019-09-12 10:05 UTC, kocsismate commented
I don't understand why this `...|false` typehint is stigmatized so much. Although I don't use it for function parameters and return types, it can certainly be useful as a property type declaration.

In the past, I had a piece of code where I lazily initialized a *nullable* property (it might be a test code though). In order to detect whether the property already has a value, I did the following:

```php
class A {
    /** @var Value|null|false */
    private $lazyProperty;

    public function getLazyProperty(): ?Value
    {
        if ($this->lazyProperty === false) {
            // initialize
        }
 
        return $this->lazyProperty;
    }
}
```

I don't know if there is a better way to achieve this, but I like the idea to be able to type hint against `false`.

2019-09-12 10:28 UTC, mattacosta commented
Note that your code would not work with booleans, which is why other languages have `undefined` or a specific `Lazy<T>` type that would use two properties to compute and return a value. So in my opinion, yes, there is a better way to achieve that.

2019-09-12 10:39 UTC, kocsismate commented
@mattacosta Staying in the realms of PHP, there is no `undefined` or generics. Probably I could have created a separate `LazyValue` class for this specific use-case, but that would have been too much overhead for this simple test class.

The other thing is that I chose `false` as an initial value because it is out of the scope of possible values as the `Value` in the example is intended to be a class. But if I had to also support `boolean`s I could also choose `0` or `"undefined"` as well.

2019-09-12 10:42 UTC, Ocramius commented
@mattacosta @kocsismate in PHP, there is a concept of "`unset` object properties", which matches what you want here.

2019-09-12 10:43 UTC, nikic commented
To add to what @Ocramius said, typed properties default to uninitialized, so you can simply use `private ?Value $lazyProperty` and check whether it's initialized in `getLazyProperty()`.

Unfortunately, there is no easy way to distinguish between an uninitialized and a null property right now (only possible via reflection), so this still falls short in practice. But generally this would be the correct way to go about it, I think.

2019-09-12 10:52 UTC, kocsismate commented
@nikic Yes, I agree to you, and I already missed an easy-to-use functionality to check uninitialized properties when I wanted to lazy-load other properties which had type declarations. As far as I remember I had to downgrade type declarations to PHPDoc at the end :/ .

Speaking about `unset`, I use PHPStan strict rules so I didn't even consider using unset properties. But this is probably another topic which falls out of the scope of the discussion about union types. :)

2019-09-12 11:41 UTC, IMSoP commented
I have always hated that typed properties added an extra "uninitialized" state, which can't be detected, and only exists in certain scenarios. I still think it was a bad design.

If you want more than one terminal value, then some kind of enum or algebraic data type is probably the ideal, and a union with specific values can emulate this a bit, e.g. `string|INVALID_ENTRY|FILE_NOT_FOUND`. Having both `null` and `false` allows you to write `string|null|false`, but you're still stuck if you want a _third_ terminal value, or if you want a lazy boolean.

2019-09-12 16:40 UTC, kocsismate commented
I admit that my `Value|null|false` solution is not elegant at all, but currently this is the easiest viable option (which won't be reported by static analyzers) for such a trivial use-case I have (a builder class for unit testing). Of course, I would welcome a mean to detect uninitialized properties besides reflection or inspecting the `var_dump()` result :D - it would certainly eliminate the need to use my workaround.

P.S: I believe the uninitialized state is a "necessary evil", otherwise we had trouble declaring non-nullable class types for properties or we ended up in a situation where Java is in now (where classes are implicitly nullable).

2019-09-12 17:17 UTC, mattacosta commented
The reason I assumed that your code could work with booleans is because if not, then the property could just as easily have been typed as `T|null|bool`, which would mean that once again, `false` does not provide anything meaningful.

All of that is irrelevant to my original question of if a restriction would be feasible though. Assuming it is, I ask because the primary argument for `false`, *as specified in the RFC*, is to support internal functions. If that argument is sound, then it would seem to be a better solution. If not, then shouldn't the RFC text be updated to include the reasoning behind including this "convenience" in actual code? There's nothing mentioning its potential impact, nor anything backing the special rules involved either.

As a side note: It also kind of sucks that the `false`-as-a-type discussion is in like five different places throughout this PR, some of which is hidden behind resolved change requests. Maybe the next RFC experiment could use the TC39 model of having each proposal be its own repository with actual issues, and this repo just be a directory of sorts. Of course then the repo would have to be transferred to the PHP organization at some point for preservation... so ugh.

2019-09-18 13:02 UTC, nikic commented on rfcs/0000-union-types-v2.md
> +At this point in time, parentheses in types are only allowed in the one case where they are necessary, which is the `?(T1|T2|...)` syntax. With further extensions to the type system (such as intersec
Removed in https://github.com/php/php-rfcs/pull/1/commits/7829b45b5dacf961ae3bfd659da873272801aa1a.

2019-09-19 20:05 UTC, markushausammann commented
Please make all RFC's available on Github like this from now on!

2019-09-24 11:19 UTC, kasparsklavins commented
> A classical example is the strpos() family of functions, which returns int|false.
>
>While it would be possible to model this less accurately as int|bool, this gives the false impression that the function can also return a true value, which makes this type information significantly less useful to humans and static analyzers both.

A similar argument could be said for, e.g., `preg_match` that returns `1|0|false`.

2019-09-25 09:18 UTC, patrickallaert commented
> Please make all RFC's available on Github like this from now on!

While I love Github, I am not sure I like the fact that for someone to take part of the discussion, he **must** create a github account (which also means being forced to accept [Github's Terms of Service](https://help.github.com/en/articles/github-terms-of-service)) :confused:.

2019-10-08 10:49 UTC, qbbr commented
Proposal+, GH RFC - good practice! Thx @nikic.

2019-11-08 03:48 UTC, mcneely commented on rfcs/0000-union-types-v2.md
> +An earlier version of this RFC proposed to use `?(T1|T2)` for nullable union types instead, to avoid having two ways of expressing nullability in PHP. However, this notation is both rather awkward sy
Why not just `?T1|T2`?

2019-11-08 04:09 UTC, mcneely commented on rfcs/0000-union-types-v2.md
> +### `false` pseudo-type
> I see what you're getting at, but rather than "legacy as soon as it's implemented" it could also be seen as a pre-cursor for a more general feature, where you can specify a union of _values_ rather than just _types_. See ["Literal Types" in the Future Scope section](https://github.com/nikic/php-rfcs/blob/union-types/rfcs/0000-union-types-v2.md#literal-types) for a brief discussion of this.

Maybe it would be better to leave false out of this proposal but flesh it out more as a part of literal types? If someone wants to use that paradigm, allowing `type false = false` would allow the end use to pull off those sort of Shenanigans without encouraging poor practices by specifically implementing them in code.

2019-11-08 08:47 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +An earlier version of this RFC proposed to use `?(T1|T2)` for nullable union types instead, to avoid having two ways of expressing nullability in PHP. However, this notation is both rather awkward sy
It's ambiguous syntax.

2019-11-08 08:54 UTC, matthieu88160 commented on rfcs/0000-union-types-v2.md
> +An earlier version of this RFC proposed to use `?(T1|T2)` for nullable union types instead, to avoid having two ways of expressing nullability in PHP. However, this notation is both rather awkward sy
What if we have more than two types, like `T1|T2|T3`, then it's become complicated to place ce question marks (`?T1|T2?|T3?` or `?T1|?T2|T3?`).
The `T1|T2|T3|null` syntax looks more comprehensive in this case.

2019-11-08 09:30 UTC, nikic commented
[**Voting**](https://wiki.php.net/rfc/union_types_v2#vote) has closed with 61 votes in favor and 5 against. As such, the RFC is **accepted**.

2019-11-08 09:30 UTC, closed without merging

2019-11-08 10:17 UTC, rask commented
Nice!

Meta: will RFCs be opened to broader discussion via GitHub in the future as well? Also would it make sense to actually merge the accepted RFCs into the repo, instead of just closing the PR?

2019-11-08 10:22 UTC, nikic commented
@rask See https://externals.io/message/107747. The tl;dr for now is: RFCs can be initially submitted against GitHub, but have to move to the PHP wiki before voting.

2019-11-08 12:48 UTC, mcneely commented on rfcs/0000-union-types-v2.md
> +An earlier version of this RFC proposed to use `?(T1|T2)` for nullable union types instead, to avoid having two ways of expressing nullability in PHP. However, this notation is both rather awkward sy
The second question mark was outside as I was asking a question. More Types would look like this `?T1|T2|T3`.

2019-11-08 12:55 UTC, mcneely commented on rfcs/0000-union-types-v2.md
> +An earlier version of this RFC proposed to use `?(T1|T2)` for nullable union types instead, to avoid having two ways of expressing nullability in PHP. However, this notation is both rather awkward sy
@majkl578 But is it really that ambiguous? The question mark already establishes to allow null.  ?T1 whis is current is the same as null|T1.  Whether someone reads that as (null|T1)|T2|T3 or null|T1|T2|T3 isn't going to make a difference.

2019-11-08 14:02 UTC, Majkl578 commented on rfcs/0000-union-types-v2.md
> +An earlier version of this RFC proposed to use `?(T1|T2)` for nullable union types instead, to avoid having two ways of expressing nullability in PHP. However, this notation is both rather awkward sy
`(null|T1)|T2|T3` and `null|T1|T2|T3` is equivalent.

Please read the discussion in this thread where this choice was discussed: https://github.com/php/php-rfcs/pull/1#discussion_r320784531

2019-11-08 14:57 UTC, kalinin-k-a commented
sad but true

2019-11-12 02:34 UTC, zzz6519003 commented
to save space？

2019-11-13 03:32 UTC, ZRayCC commented
It's terrible feature. I can't accept that. I like that one variable has one type. 
In a team, some people will make the code worst because of the union types.  It a bad standard and hardly trace.